import {enterPump,waitPump} from './pump-helpers.js';
/* global document, window */
import {test,expect} from '@playwright/test';
import {GAMES} from '../../src/arcade-room/catalog.js';
test.beforeEach(async({page})=>{await page.clock.install({time:new Date('2026-01-01T00:00:00Z')});await page.goto('./');await expect(page.locator('[data-start="drive"].start')).toBeEnabled();await page.clock.pauseAt(new Date('2026-01-01T00:01:00Z'));});
for(const [kind,g] of Object.entries(GAMES))test(`${kind}: input, pause, result, continue and save`,async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.getByRole('button',{name:`${g.name}의 ${g.title} 시작`}).click();await enterPump(page);await expect(page.locator('#app')).toHaveAttribute('data-state','playing');
 await expect(page.getByRole('button',{name:'소리 끄기',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:'멤버 음성 끄기',exact:true})).toHaveAttribute('aria-pressed','true');
 if(kind==='drive'){await page.clock.runFor(800);await page.locator('.field-controls button[data-active="true"]').first().click();await expect(page.locator('#score')).not.toHaveText('0');}
 if(kind==='blocks'){await page.getByRole('button',{name:'점프 ↑'}).click();await page.clock.runFor(350);await page.getByRole('button',{name:'방울 ○'}).click();}
 if(kind==='photo'){await page.locator('.field-controls button').nth(0).click();await expect(page.locator('.field-controls button').nth(0)).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'빵 섞기 · 2회'}).click();await expect(page.getByRole('button',{name:'빵 섞기 · 1회'})).toBeVisible();}
 if(kind==='rhythm'){await page.clock.runFor(2000);const bounds=await page.locator('#game').boundingBox();await page.mouse.click(bounds.x+75/480*bounds.width,bounds.y+136/600*bounds.height);await expect(page.locator('#score')).not.toHaveText('0');await expect(page.locator('.pump-pad button')).toHaveCount(0);}
 if(kind==='catch'){await page.locator('.field-controls button').nth(0).click();await expect(page.locator('.field-controls button').nth(0)).toHaveAttribute('aria-pressed','true');await expect(page.locator('#extra')).toHaveText('3');}
 await page.screenshot({path:info.outputPath('game.png'),fullPage:true});await page.getByRole('button',{name:'잠깐 쉬기 Ⅱ'}).click();const time=await page.locator('#time').innerText();await page.clock.fastForward(65000);await expect(page.locator('#time')).toHaveText(time);await page.getByRole('button',{name:'계속하기 ▶'}).click();await waitPump(page);await page.clock.fastForward(61000);await expect(page.locator('#app')).toHaveAttribute('data-state','result');await expect(page.getByText('진행 상황과 최고 기록은 이 기기에 저장했어요.',{exact:true})).toBeVisible();await page.locator('#overlay [data-start]').first().click();await expect(page.locator('#score')).toHaveText('0');expect(errors).toEqual([]);
});
test('small viewport keeps movement and direct pump controls reachable without overflow',async({page})=>{await page.setViewportSize({width:320,height:568});for(const kind of ['blocks','rhythm','catch']){await page.locator(`[data-start="${kind}"].start`).click();await enterPump(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await expect(page.locator('.game-controls')).toBeInViewport();const bounds=await page.locator('.game-controls').boundingBox();expect(bounds.y+bounds.height).toBeLessThanOrEqual(568);await page.getByRole('button',{name:'잠깐 쉬기 Ⅱ'}).click();await page.getByRole('button',{name:'오락실로 돌아가기'}).click();}});
test('rhythm correction persists and help restores keyboard focus',async({page})=>{await page.locator('[data-start="rhythm"].start').click();await enterPump(page);await page.getByRole('button',{name:'하는 방법'}).click();await page.locator('#offset').fill('100');await expect(page.locator('#offset-value')).toHaveText('100ms');await page.getByRole('button',{name:'계속하기 ▶'}).click();await waitPump(page);await expect(page.locator('#game')).toBeFocused();await page.reload();await page.locator('[data-start="rhythm"].start').click();await enterPump(page);await page.getByRole('button',{name:'계속하기 ▶'}).click();await waitPump(page);await page.getByRole('button',{name:'하는 방법'}).click();await expect(page.locator('#offset')).toHaveValue('100');});
