/* global localStorage,document,window */
import {test,expect} from '@playwright/test';
import {createGame} from '../../src/arcade-room/model.js';
import {emptyProgress,snapshotRound,PROGRESS_KEY} from '../../src/arcade-room/progress.js';
async function open(page,s){const p=emptyProgress();p.games.photo={...p.games.photo,stage:s.stage,highest:s.stage,snapshot:snapshotRound(s)};await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,value);},{key:PROGRESS_KEY,value:JSON.stringify(p)});await page.clock.install({time:new Date('2026-01-01T00:00:00Z')});await page.goto('./');await page.clock.pauseAt(new Date('2026-01-01T00:01:00Z'));await page.locator('[data-start="photo"].start').click();await page.locator('[data-resume]').click();}
test('an 8x8 wrapper must be completely removed before stage clear and the next stage has more bread',async({page},info)=>{const s=createGame('photo',{stage:3,seed:7});s.collected=999;s.breadCover.fill(true);for(let i=140;i<148;i++)s.breadCover[i]=false;await open(page,s);await expect(page.locator('#goal')).toHaveText('0 / 1 신라빵');await expect(page.locator('#app')).toHaveAttribute('data-state','playing');await page.screenshot({path:info.outputPath('hidden-bread.png'),fullPage:true});await page.locator('[data-act="rolling-pin"]').click();await page.locator('.field-controls [data-act="147"]').click();await page.clock.runFor(12000);await expect(page.locator('#result-title')).toHaveText('스테이지 3 클리어!');await page.locator('.result-paper [data-start="photo"]').click();await expect(page.locator('#goal')).toHaveText('0 / 2 신라빵');await expect(page.locator('.field-controls button')).toHaveCount(400);});
test('20x20 board supports zoom, scrolling to the last cell, keyboard and saved wrapper progress',async({page},info)=>{const s=createGame('photo',{stage:1,seed:7});s.breadCover[0]=true;s.breadCover[1]=true;await open(page,s);await expect(page.locator('.field-controls button')).toHaveCount(400);await page.locator('[data-bread-zoom]').click();await expect(page.locator('[data-bread-zoom]')).toHaveAttribute('aria-pressed','true');const last=page.locator('.field-controls [data-act="399"]');await last.click();await expect(last).toHaveAttribute('aria-pressed','true');await last.focus();await page.keyboard.press('ArrowLeft');await expect(page.locator('.field-controls [data-act="398"]')).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('20x20-zoom.png'),fullPage:true});await page.locator('[data-bread-zoom]').click();await page.locator('[data-pause]').click();const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).games.photo.snapshot,PROGRESS_KEY);expect(saved.breadCover.slice(0,3)).toEqual([true,true,false]);await page.reload();await page.locator('[data-start="photo"].start').click();await page.locator('[data-resume]').click();await expect(page.locator('.field-controls [data-act="0"]')).toHaveAttribute('aria-label',/드러난 칸/);await expect(page.locator('.field-controls button')).toHaveCount(400);});

test('an older 10x10 late-stage save expands to 20x20 and persists',async({page})=>{const s=createGame('photo',{stage:5,seed:7});s.stage=12;s.board=s.board.slice(0,100);s.hint=[];s.bakeryVersion=1;delete s.breadCover;s.elapsed=15;s.remaining=45;s.moves=12;await open(page,s);await expect(page.locator('.field-controls button')).toHaveCount(400);await expect(page.locator('#time')).toHaveText('165초');await page.locator('[data-pause]').click();const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).games.photo.snapshot,PROGRESS_KEY);expect(saved.stage).toBe(12);expect(saved.bakeryVersion).toBe(2);expect(saved.breadCover).toHaveLength(400);await page.reload();await page.locator('[data-start="photo"].start').click();await expect(page.locator('.field-controls button')).toHaveCount(400);});
