/* global localStorage, window, document */
import {test,expect} from '@playwright/test';
import {createGame,stageBoardSize,availableSwap} from '../../src/arcade-room/model.js';
import {emptyProgress,snapshotRound,PROGRESS_KEY} from '../../src/arcade-room/progress.js';
async function open(page,s){const p=emptyProgress();p.games[s.kind]={...p.games[s.kind],stage:s.stage,highest:s.stage,snapshot:snapshotRound(s)};await page.addInitScript(({key,value})=>{localStorage.setItem(key,value);const Native=window.Audio;window.revisionClips=[];window.Audio=class extends Native{constructor(src){super(src);window.revisionClips.push(this);}};},{key:PROGRESS_KEY,value:JSON.stringify(p)});await page.clock.install({time:new Date('2026-01-01T00:00:00Z')});await page.goto('./');await page.clock.pauseAt(new Date('2026-01-01T00:01:00Z'));await page.locator(`[data-start="${s.kind}"].start`).click();await page.locator('[data-resume]').click();}
for(const stage of [2,5])test(`Zena stage ${stage}: growing board remains playable by touch and keyboard`,async({page},info)=>{const s=createGame('photo',{stage,seed:7}),size=stageBoardSize(stage),pair=availableSwap(s.board);await open(page,s);const cells=page.locator('.field-controls button');await expect(cells).toHaveCount(size*size);await cells.nth(size*size-1).focus();await page.keyboard.press('ArrowLeft');await expect(cells.nth(size*size-2)).toBeFocused();for(const i of pair)await cells.nth(i).click();await expect(page.locator('#score')).not.toHaveText('0');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`zena-stage-${stage}.png`),fullPage:true});});
test('May honey singing continues across the next stage and ends after a minute',async({page})=>{const s=createGame('blocks',{seed:7});s.popped=17;s.spawn=10;s.enemies=[{x:90,y:520,home:0,dir:1,trapped:4,vy:0,think:.8,angry:false}];await open(page,s);await page.clock.runFor(50);await expect(page.locator('#result-title')).toHaveText('스테이지 1 클리어!');await expect.poll(()=>page.evaluate(()=>window.revisionClips.find(a=>a.src.includes('may-song'))?.paused)).toBe(false);expect(await page.evaluate(()=>window.revisionClips.find(a=>a.src.includes('may-song')).loop)).toBe(false);await page.locator('.result-paper [data-start="blocks"]').click();await expect(page.locator('.stage-goal')).toContainText('STAGE 2');expect(await page.evaluate(()=>window.revisionClips.filter(a=>a.src.includes('may-song')).length)).toBe(1);expect(await page.evaluate(()=>window.revisionClips.find(a=>a.src.includes('may-song')).paused)).toBe(false);await page.clock.fastForward(60100);expect(await page.evaluate(()=>window.revisionClips.every(a=>!a.loop||a.paused))).toBe(true);});
test('Zena music is awarded only after explicitly collecting her song item',async({page})=>{const s=createGame('photo',{seed:7});s.songDrops=1;await open(page,s);expect(await page.evaluate(()=>window.revisionClips.filter(a=>a.src.includes('zena-song')).length)).toBe(0);await page.locator('[data-act="song-pickup"]').click();await expect.poll(()=>page.evaluate(()=>window.revisionClips.find(a=>a.src.includes('zena-song'))?.paused)).toBe(false);await expect(page.locator('[data-act="song-pickup"]')).toBeDisabled();await page.locator('[data-pause]').click();expect(await page.evaluate(()=>window.revisionClips.find(a=>a.src.includes('zena-song')).paused)).toBe(true);await page.clock.fastForward(61000);await page.locator('[data-resume]').click();await expect.poll(()=>page.evaluate(()=>window.revisionClips.find(a=>a.src.includes('zena-song'))?.paused)).toBe(false);});

test('legacy Zena shuffle keeps cell controls aligned',async({page})=>{const s=createGame('photo',{seed:7});s.stage=3;s.board=s.board.slice(0,36);s.breadCover=Array(36).fill(false);s.hint=[];await open(page,s);await page.locator('[data-act="shuffle"]').click();const cells=page.locator('.field-controls button');await expect(cells).toHaveCount(36);await cells.nth(35).focus();await page.keyboard.press('ArrowLeft');await expect(cells.nth(34)).toBeFocused();await expect(cells.nth(35)).toHaveAttribute('aria-label',/6행 6열/);});
test('May result song resumes on focus and when continuing from a blurred result',async({page})=>{const s=createGame('blocks',{seed:7});s.popped=17;s.spawn=10;s.enemies=[{x:90,y:520,home:0,dir:1,trapped:4,vy:0,think:.8,angry:false}];await open(page,s);await page.clock.runFor(50);await expect(page.locator('#result-title')).toHaveText('스테이지 1 클리어!');await expect.poll(()=>page.evaluate(()=>window.revisionClips.find(a=>a.src.includes('may-song'))?.paused)).toBe(false);await page.evaluate(()=>window.dispatchEvent(new window.Event('blur')));expect(await page.evaluate(()=>window.revisionClips.find(a=>a.src.includes('may-song')).paused)).toBe(true);await page.evaluate(()=>window.dispatchEvent(new window.Event('focus')));await expect.poll(()=>page.evaluate(()=>window.revisionClips.find(a=>a.src.includes('may-song')).paused)).toBe(false);await page.evaluate(()=>window.dispatchEvent(new window.Event('blur')));await page.locator('.result-paper [data-start="blocks"]').click();await expect.poll(()=>page.evaluate(()=>window.revisionClips.find(a=>a.src.includes('may-song')).paused)).toBe(false);});
