/* global window, document, localStorage */
import {test,expect} from '@playwright/test';
import {createGame} from '../../src/arcade-room/model.js';
import {LIV_ATTACKS} from '../../src/arcade-room/runner.js';
import {RESCENE_SONGS} from '../../src/arcade-room/music.js';
import {emptyProgress,snapshotRound,PROGRESS_KEY,stageGoal} from '../../src/arcade-room/progress.js';
import {fakeApi} from './youtube-helpers.js';
async function open(page,kind){
 const s=createGame('catch',{seed:7});s.spawn=15;s.gates=[];s.enemies=[];s.pickups=[{lane:1,y:440,kind}];const p=emptyProgress();p.games.catch.snapshot=snapshotRound(s);
 await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,value);const Native=window.AudioContext||window.webkitAudioContext;window.musicStarts=0;window.AudioContext=class extends Native{createOscillator(){window.musicStarts++;return super.createOscillator();}};},{key:PROGRESS_KEY,value:JSON.stringify(p)});
 await page.clock.install({time:new Date('2026-01-01T00:00:00Z')});await page.goto('./');await page.evaluate(()=>document.fonts.ready);await page.clock.pauseAt(new Date('2026-01-01T00:01:00Z'));await page.locator('[data-start="catch"].start').click();await page.locator('[data-resume]').click();await page.clock.runFor(100);
}
const snapshot=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)).games.catch.snapshot,PROGRESS_KEY);
for(const song of Object.values(RESCENE_SONGS))test(`Liv ${song.title} pickup activates its attack and the matching official song`,async({page},info)=>{
 await fakeApi(page);await open(page,song.id);await expect(page.locator('#music-status')).toContainText('재생 중 · '+song.title);await page.clock.runFor(100);await expect(page.locator('#powerup-status')).toContainText(song.title);expect(await page.evaluate(()=>window.ytPlayers.at(-1).loaded.videoId)).toBe(song.videoId);await expect(page.locator('.pump-video-card a')).toHaveAttribute('href','https://www.youtube.com/watch?v='+song.videoId);const box=await page.locator('#pump-video iframe').boundingBox();expect(box.height).toBeGreaterThanOrEqual(200);expect(box.width).toBeGreaterThanOrEqual(200);const before=await page.evaluate(()=>window.musicStarts);await page.clock.runFor(300);expect(await page.evaluate(()=>window.musicStarts)).toBe(before);await expect(page.locator('#powerup-status')).toContainText(LIV_ATTACKS[song.id].name);await page.screenshot({path:info.outputPath('liv-'+song.id+'.png'),fullPage:true});await page.locator('[data-pause]').click();const s=await snapshot(page);expect(s.item).toBe(song.id);expect(s.itemTime).toBeGreaterThan(9);expect(s.shots.every(b=>b.kind===song.id)).toBe(true);if(song.id==='love-attack')await page.screenshot({path:info.outputPath('liv-love-attack.png'),fullPage:true});expect(await page.evaluate(()=>window.ytPlayers.at(-1).status)).toBe(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('Liv song outlasts the attack, resumes its saved position and respects sound controls',async({page})=>{
 await fakeApi(page);await open(page,'love-attack');await expect(page.locator('#music-status')).toContainText('재생 중');await page.clock.runFor(1300);await page.locator('[data-pause]').click();const before=await snapshot(page);await page.reload();await page.locator('[data-start="catch"].start').click();await expect(page.locator('#pump-video iframe')).toHaveCount(0);await page.locator('[data-resume]').click();await expect(page.locator('#music-status')).toContainText('재생 중');expect(await page.evaluate(()=>window.ytPlayers.at(-1).loaded.startSeconds)).toBeCloseTo(20-before.songTime,2);await page.locator('[data-sound]').click();expect(await page.evaluate(()=>window.ytPlayers.at(-1).muted)).toBe(true);await page.locator('[data-sound]').click();expect(await page.evaluate(()=>window.ytPlayers.at(-1).muted)).toBe(false);const count=await page.evaluate(()=>window.musicStarts);await page.clock.runFor(9000);await expect(page.locator('#pump-video iframe')).toHaveCount(1);await expect(page.locator('#powerup-status')).toContainText('LOVE ATTACK');await page.clock.runFor(10500);expect(await page.evaluate(()=>window.ytPlayers.every(p=>p.destroyed))).toBe(true);await expect(page.locator('#pump-video iframe')).toHaveCount(0);expect(await page.evaluate(()=>window.musicStarts)).toBeGreaterThan(count);await expect(page.locator('#app')).toHaveAttribute('data-state','playing');await page.locator('[data-pause]').click();const after=await snapshot(page);expect(after.itemPickups).toBe(before.itemPickups);expect(after.item).toBe('love-attack');expect(after.songItem).toBe('');
});
test('Liv keeps its attack on a video failure and can retry without another pickup',async({page})=>{
 await page.route('https://www.youtube.com/iframe_api',r=>r.abort());await open(page,'pinball');await expect(page.locator('#music-status')).toContainText('불러오지 못했어요');await expect(page.locator('#app')).toHaveAttribute('data-state','playing');await expect(page.locator('#powerup-status')).toContainText('Pinball');await page.unroute('https://www.youtube.com/iframe_api');await fakeApi(page);await page.locator('[data-retry-music]').click();await expect(page.locator('#music-status')).toContainText('재생 중 · Pinball');await page.locator('[data-pause]').click();expect((await snapshot(page)).itemPickups).toBe(1);await page.locator('[data-leave]').click();expect(await page.evaluate(()=>window.ytPlayers.every(p=>p.destroyed))).toBe(true);
});

test('Liv keeps the official player and lane controls visible on a small phone',async({page},info)=>{
 await page.setViewportSize({width:320,height:568});await fakeApi(page);await open(page,'love-attack');await expect(page.locator('#music-status')).toContainText('재생 중');const video=await page.locator('#pump-video iframe').boundingBox(),controls=await page.locator('.game-controls').boundingBox(),field=await page.locator('.playfield').boundingBox(),toast=await page.locator('.signature-toast').boundingBox();expect(toast.width).toBeLessThan(field.width/2);expect(video.width).toBeGreaterThanOrEqual(200);expect(video.height).toBeGreaterThanOrEqual(200);expect(controls.y+controls.height).toBeLessThanOrEqual(568);await page.screenshot({path:info.outputPath('liv-small-phone.png'),fullPage:true});await page.clock.runFor(20500);await expect(page.locator('#pump-video iframe')).toHaveCount(0);const idle=await page.locator('.game-controls').boundingBox();expect(idle.y).toBeCloseTo(controls.y,0);
});

test('collecting overlapping items plays one song and keeps it after an enemy dies',async({page})=>{
 await fakeApi(page);const s=createGame('catch',{seed:7});s.spawn=15;s.gates=[];s.pickups=[{lane:1,y:440,kind:'love-attack'},{lane:1,y:445,kind:'pinball'}];s.enemies=[{id:9,lane:1,y:440,hp:1,maxHp:1,boss:false}];const p=emptyProgress();p.games.catch.snapshot=snapshotRound(s);
 await page.addInitScript(({key,value})=>localStorage.setItem(key,value),{key:PROGRESS_KEY,value:JSON.stringify(p)});
 await open(page,'love-attack');await page.clock.runFor(1500);await expect(page.locator('#music-status')).toContainText('LOVE ATTACK');expect(await page.evaluate(()=>window.ytPlayers.length)).toBe(1);await page.locator('[data-pause]').click();const saved=await snapshot(page);expect(saved.defeated).toBe(1);expect(saved.itemPickups).toBe(1);expect(saved.pickups).toEqual([]);expect(saved.itemCooldown).toBeGreaterThan(22);
});

test('a boss clear keeps the item song playing beside the compact result until its listening time ends',async({page},info)=>{
 await fakeApi(page);const s=createGame('catch',{seed:7});s.spawn=15;s.gates=[];s.bossSpawned=true;s.defeated=stageGoal('catch',1).target-1;s.enemies=[{id:8,lane:1,y:430,hp:1,maxHp:1,boss:true}];s.item='love-attack';s.itemTime=25;s.songItem='love-attack';s.songTime=15;s.itemCooldown=19;s.itemPickups=1;const p=emptyProgress();p.games.catch.snapshot=snapshotRound(s);
 await page.addInitScript(({key,value})=>localStorage.setItem(key,value),{key:PROGRESS_KEY,value:JSON.stringify(p)});await open(page,'love-attack');await expect(page.locator('#app')).toHaveAttribute('data-state','result');await expect(page.locator('#overlay>.pump-video-card iframe')).toHaveCount(1);expect(await page.evaluate(()=>window.ytPlayers.at(-1).status)).toBe(1);await page.screenshot({path:info.outputPath('liv-result-song.png'),fullPage:true});await page.clock.runFor(3000);expect(await page.evaluate(()=>window.ytPlayers.at(-1).destroyed)).not.toBe(true);await page.clock.runFor(13000);await expect(page.locator('#overlay>.pump-video-card')).toHaveCount(0);await expect(page.locator('[data-song-replay]')).toBeVisible();
});

test('Liv retry and reload retain the next song instead of returning to Love Attack',async({page})=>{
 await fakeApi(page);await open(page,'love-attack');await expect(page.locator('#music-status')).toContainText('LOVE ATTACK');await page.locator('[data-pause]').click();await page.locator('[data-restart]').click();await page.locator('[data-pause]').click();expect((await snapshot(page)).itemSongIndex).toBe(1);
 await page.reload();await page.locator('[data-start="catch"].start').click();await page.locator('[data-resume]').click();
 let pickup;
 for(let i=0;i<10;i++){await page.clock.runFor(500);await page.locator('[data-pause]').click();pickup=(await snapshot(page)).pickups[0];await page.locator('[data-resume]').click();if(pickup)break;}
 expect(pickup?.kind).toBe('pinball');await page.keyboard.press(String(pickup.lane+1));await page.clock.runFor(2200);await expect(page.locator('#music-status')).toContainText('Pinball');
});
