/* global window, localStorage */
import {test,expect} from '@playwright/test';
import {createGame} from '../../src/arcade-room/model.js';
import {emptyProgress,snapshotRound,PROGRESS_KEY} from '../../src/arcade-room/progress.js';
import {waitPump,enterPump} from './pump-helpers.js';
async function audit(page){await page.addInitScript(()=>{const Audio=window.Audio,Context=window.AudioContext||window.webkitAudioContext;window.songs=[];window.Audio=class extends Audio{constructor(src){super(src);if(src.includes('music/'))window.songs.push(this);}};window.musicContext=null;window.AudioContext=class extends Context{constructor(){super();this.audit=this.createAnalyser();this.audit.connect(this.destination);window.musicContext=this;}createGain(){const g=super.createGain(),connect=g.connect.bind(g);g.connect=t=>connect(t===this.destination?this.audit:t);return g;}};});}
const rms=page=>page.evaluate(()=>{const c=window.musicContext;if(!c)return 0;const a=new Float32Array(c.audit.fftSize);c.audit.getFloatTimeDomainData(a);return Math.sqrt(a.reduce((v,n)=>v+n*n,0)/a.length);});
test('Pump selects each real song, previews audible music, starts the chosen chart and preserves it',async({page},info)=>{
 await audit(page);await page.clock.install({time:new Date('2026-01-01T00:00:00Z')});await page.goto('./');await page.clock.pauseAt(new Date('2026-01-01T00:01:00Z'));await page.locator('[data-start="rhythm"].start').click();await expect(page.locator('#app')).toHaveAttribute('data-state','songs');
 for(const id of ['five-steps','sea-breeze','neon-rush']){await page.locator(`[data-song="${id}"]`).click();await page.locator('[data-song-preview]').click();await expect.poll(()=>page.evaluate(()=>window.songs.at(-1).currentSrc)).toContain(id+'.mp3');await expect.poll(()=>page.evaluate(()=>window.songs.at(-1).paused)).toBe(false);await expect.poll(()=>rms(page)).toBeGreaterThan(.005);}
 await page.locator('[data-song-level="6"]').click();await page.screenshot({path:info.outputPath('pump-song-selection.png'),fullPage:true});await page.locator('[data-song-start]').click();await waitPump(page);await expect(page.locator('.music-credit')).toContainText('네온 러시 · 144 BPM');await expect(page.locator('.stage-goal b')).toHaveText('STAGE 6');await expect.poll(()=>rms(page)).toBeGreaterThan(.005);await page.clock.runFor(300);await page.locator('[data-pause]').click();await expect.poll(()=>rms(page)).toBeLessThan(.00001);expect(await page.evaluate(()=>window.songs.every(a=>a.paused))).toBe(true);
 const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).games.rhythm.snapshot,PROGRESS_KEY);expect(saved.songId).toBe('neon-rush');expect(saved.stage).toBe(6);expect(saved.elapsed).toBeGreaterThan(.2);
 await page.reload();await page.locator('[data-start="rhythm"].start').click();await enterPump(page);await page.locator('[data-resume]').click();await waitPump(page);await expect(page.locator('.music-credit')).toContainText('네온 러시');expect(await page.evaluate(()=>window.songs.at(-1).currentTime)).toBeGreaterThan(.1);
 await page.locator('[data-music]').click();await expect.poll(()=>rms(page)).toBeLessThan(.00001);await page.locator('[data-retry-music]').click();await waitPump(page);await expect.poll(()=>rms(page)).toBeGreaterThan(.005);
});
test('Pump audio failure pauses without consuming lives, and retry restores real playback',async({page})=>{
 await audit(page);await page.route('**/music/*.mp3',r=>r.abort());await page.goto('./');await page.locator('[data-start="rhythm"].start').click();await page.locator('[data-song-start]').click();await expect(page.locator('#app')).toHaveAttribute('data-state','paused');await expect(page.locator('#music-status')).toContainText(/못했어요|막혔어요/);await expect(page.locator('#lives')).toHaveAttribute('aria-label','남은 목숨 3개');
 await page.unroute('**/music/*.mp3');await page.locator('[data-retry-music]').click();await waitPump(page);await expect(page.locator('#app')).toHaveAttribute('data-state','playing');await expect.poll(()=>rms(page)).toBeGreaterThan(.005);
});
test('May chains nearby trapped enemies with F, retains lives and restores the harder round',async({page},info)=>{
 const s=createGame('blocks',{stage:5,hearts:2,seed:7});s.spawn=10;s.enemies=[150,220,290,420].map(x=>({x,y:536,home:0,dir:1,trapped:4,vy:0,think:1,angry:false}));const p=emptyProgress();p.games.blocks={stage:5,highest:5,hearts:2,snapshot:snapshotRound(s)};
 await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,value);},{key:PROGRESS_KEY,value:JSON.stringify(p)});await page.clock.install({time:new Date('2026-01-01T00:00:00Z')});await page.goto('./');await page.clock.pauseAt(new Date('2026-01-01T00:01:00Z'));await page.locator('[data-start="blocks"].start').click();await page.locator('[data-resume]').click();await page.keyboard.press('f');await expect(page.locator('#extra')).toHaveText('3');await expect(page.locator('#lives')).toHaveAttribute('aria-label','남은 목숨 2개');await expect(page.locator('#app')).toHaveAttribute('data-state','playing');await page.screenshot({path:info.outputPath('may-chain.png'),fullPage:true});await page.clock.runFor(4100);await page.locator('[data-pause]').click();const read=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)).games.blocks.snapshot,PROGRESS_KEY);const before=await read();expect(before.enemies.some(e=>e.angry)).toBe(true);await page.reload();await page.locator('[data-start="blocks"].start').click();const after=await read();expect(after.popped).toBe(3);expect(after.hearts).toBe(2);expect(after.enemies).toEqual(before.enemies);
});
test('Pump continues the chosen song and next stage after a completed-round reload; a new selection resets only its own run',async({page})=>{
 const p=emptyProgress();p.games.rhythm={stage:7,highest:7,hearts:2,snapshot:null};p.games.blocks.highest=9;
 await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key)){localStorage.setItem(key,value);localStorage.setItem('rescene.rhythm.song','neon-rush');}},{key:PROGRESS_KEY,value:JSON.stringify(p)});
 await page.clock.install({time:new Date('2026-01-01T00:00:00Z')});await page.goto('./');await page.clock.pauseAt(new Date('2026-01-01T00:01:00Z'));await page.locator('[data-start="rhythm"].start').click();await enterPump(page);await expect(page.locator('.stage-goal b')).toHaveText('STAGE 7');await expect(page.locator('.music-credit')).toContainText('네온 러시');await expect(page.locator('#lives')).toHaveAttribute('aria-label','남은 목숨 2개');
 await page.locator('[data-pump-picker]').click();await page.locator('[data-song="sea-breeze"]').click();await page.locator('[data-song-level="3"]').click();await page.locator('[data-song-start]').click();await waitPump(page);await expect(page.locator('.stage-goal b')).toHaveText('STAGE 3');await expect(page.locator('.music-credit')).toContainText('바닷바람 스텝');await expect(page.locator('#lives')).toHaveAttribute('aria-label','남은 목숨 3개');expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).games.blocks.highest,PROGRESS_KEY)).toBe(9);
});
