/* global localStorage, window */
import {test,expect} from '@playwright/test';
import {createGame,availableSwap} from '../../src/arcade-room/model.js';
import {emptyProgress,snapshotRound,PROGRESS_KEY} from '../../src/arcade-room/progress.js';
async function fixture(page,kind){const s=createGame(kind,{seed:7}),p=emptyProgress();p.games[kind].snapshot=snapshotRound(s);await page.addInitScript(({key,value})=>localStorage.setItem(key,value),{key:PROGRESS_KEY,value:JSON.stringify(p)});await page.clock.install({time:new Date('2026-01-01T00:00:00Z')});await page.goto('./');await page.locator(`[data-start="${kind}"].start`).click();await page.clock.pauseAt(new Date('2026-01-01T00:01:00Z'));await page.getByRole('button',{name:'계속하기 ▶'}).click();return s;}
test('bread swaps via touch targets score and do not consume a second move from click duplication',async({page,isMobile})=>{const s=await fixture(page,'photo'),pair=availableSwap(s.board);for(const i of pair){const b=page.locator('.field-controls button').nth(i);if(isMobile)await b.tap();else await b.click();}await expect(page.locator('#score')).not.toHaveText('0');await expect(page.locator('#extra')).toHaveText('17');});
test('Liv chooses a gate, gains a squad and cannot use unearned support',async({page,isMobile},info)=>{
 await fixture(page,'catch');await expect(page.locator('.skill-button')).toBeDisabled();const lane=page.locator('.field-controls button').nth(0);if(isMobile)await lane.tap();else await lane.click();await page.clock.runFor(4500);await expect(page.locator('#extra')).toHaveText('7');await expect(page.locator('.skill-button')).toBeDisabled();await page.screenshot({path:info.outputPath('liv-gate-squad.png')});await page.keyboard.press('ArrowRight');await expect(page.locator('.field-controls button').nth(1)).toHaveAttribute('aria-pressed','true');
});
test('explicit mute survives changing games in this tab',async({page})=>{await fixture(page,'photo');await page.getByRole('button',{name:'소리 끄기',exact:true}).click();await page.getByRole('button',{name:'멤버 음성 끄기',exact:true}).click();await page.getByRole('button',{name:'잠깐 쉬기 Ⅱ'}).click();await page.getByRole('button',{name:'오락실로 돌아가기'}).click();await page.locator('[data-start="rhythm"].start').click();await expect(page.getByRole('button',{name:'소리 켜기',exact:true})).toHaveAttribute('aria-pressed','false');await expect(page.getByRole('button',{name:'멤버 음성 켜기',exact:true})).toHaveAttribute('aria-pressed','false');});

test('May keeps moving while jump is pressed and stops on releasing the movement key',async({page})=>{await fixture(page,'blocks');await page.keyboard.down('ArrowRight');await page.clock.runFor(300);await page.keyboard.press('Space');await page.clock.runFor(500);await page.keyboard.up('ArrowRight');await page.getByRole('button',{name:'잠깐 쉬기 Ⅱ'}).click();const read=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)).games.blocks.snapshot,PROGRESS_KEY);const before=await read();expect(before.player.x).toBeGreaterThan(225);expect(before.player.y).toBeLessThan(536);await page.getByRole('button',{name:'계속하기 ▶'}).click();await page.clock.runFor(400);await page.getByRole('button',{name:'잠깐 쉬기 Ⅱ'}).click();expect((await read()).player.x).toBe(before.player.x);});

test('starting a fresh game unlocks native effect audio without a sound-toggle click',async({page})=>{await page.addInitScript(()=>{const Native=window.AudioContext||window.webkitAudioContext;window.effectContexts=[];window.AudioContext=class extends Native{constructor(...args){super(...args);window.effectContexts.push(this);}};});await fixture(page,'drive');await expect.poll(()=>page.evaluate(()=>window.effectContexts.some(c=>c.state==='running'))).toBe(true);await expect(page.getByRole('button',{name:'소리 끄기',exact:true})).toBeVisible();});
test('touching jump while holding movement does not release the other pointer',async({page,isMobile})=>{test.skip(!isMobile,'Requires a touch-enabled context');await fixture(page,'blocks');const move=page.getByRole('button',{name:'오른쪽으로 이동'}),box=await move.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.clock.runFor(200);await page.getByRole('button',{name:'점프 ↑'}).tap();await page.clock.runFor(500);await page.mouse.up();await page.getByRole('button',{name:'잠깐 쉬기 Ⅱ'}).click();const s=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).games.blocks.snapshot,PROGRESS_KEY);expect(s.player.x).toBeGreaterThan(210);});

test('May reverses with keyboard and touch, fires backwards and keeps that facing after stopping',async({page,isMobile},info)=>{
 await fixture(page,'blocks');await page.keyboard.down('ArrowRight');await page.clock.runFor(150);await page.keyboard.press('x');await page.keyboard.up('ArrowRight');await page.keyboard.press('f');
 await page.getByRole('button',{name:'잠깐 쉬기 Ⅱ'}).click();const read=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)).games.blocks.snapshot,PROGRESS_KEY);let s=await read();expect(s.player.facing).toBe(-1);expect(s.player.dir).toBe(0);expect(s.bubbles[0].vx).toBe(-260);
 await page.getByRole('button',{name:'계속하기 ▶'}).click();await page.clock.runFor(300);const turn=page.getByRole('button',{name:'제자리 뒤돌기'});if(isMobile)await turn.tap();else await turn.click();await page.getByRole('button',{name:'방울 ○'}).click();
 await page.getByRole('button',{name:'잠깐 쉬기 Ⅱ'}).click();s=await read();expect(s.player.facing).toBe(1);expect(s.bubbles.some(b=>b.vx===260)).toBe(true);
 await page.getByRole('button',{name:'계속하기 ▶'}).click();await page.getByRole('button',{name:'왼쪽으로 이동'}).click();await page.screenshot({path:info.outputPath('may-facing-left.png')});await page.getByRole('button',{name:'잠깐 쉬기 Ⅱ'}).click();expect((await read()).player.facing).toBe(-1);
});
