/* global window, localStorage */
import {test,expect} from '@playwright/test';
import {createGame} from '../../src/arcade-room/model.js';
import {emptyProgress,snapshotRound,PROGRESS_KEY} from '../../src/arcade-room/progress.js';
import {stageItemSong} from '../../src/arcade-room/stage-songs.js';
async function open(page,s){const p=emptyProgress();p.games[s.kind]={...p.games[s.kind],stage:s.stage,highest:s.stage,snapshot:snapshotRound(s)};await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,value);const Native=window.Audio;window.stageClips=[];window.Audio=class extends Native{constructor(src){super(src);window.stageClips.push({src,audio:this});}};},{key:PROGRESS_KEY,value:JSON.stringify(p)});await page.clock.install({time:new Date('2026-01-01T00:00:00Z')});await page.goto('./');await page.clock.pauseAt(new Date('2026-01-01T00:01:00Z'));await page.locator(`[data-start="${s.kind}"].start`).click();await page.locator('[data-resume]').click();}
for(const kind of ['drive','blocks','photo'])test(`${kind}: stage two item plays its stage song once for 60 seconds`,async({page})=>{const s=createGame(kind,{stage:2,seed:7});s.spawn=15;if(kind==='drive')s.objects=[{id:0,lane:1,y:455,kind:'song'}];if(kind==='blocks'){s.enemies=[];s.items=[{x:90,y:514,kind:'honey',ttl:12}];}if(kind==='photo')s.songDrops=1;await open(page,s);if(kind==='photo')await page.locator('[data-act="song-pickup"]').click();else await page.clock.runFor(50);const song=stageItemSong(kind,2);await expect(page.locator('#voice-preview-status')).toContainText(song.title);await expect.poll(()=>page.evaluate(file=>{const a=window.stageClips.find(c=>c.src===file)?.audio;return a?{loop:a.loop,playing:!a.paused,duration:Math.round(a.duration*10)/10}:null;},song.file)).toEqual({loop:false,playing:true,duration:60});await expect(page.locator('#powerup-status')).toContainText('다음 노래 아이템');await page.locator('[data-pause]').click();expect(await page.evaluate(()=>window.stageClips.every(c=>c.audio.paused))).toBe(true);});
test('May song moves past the old 3.5 second excerpt with a real non-looping 60 second file',async({page})=>{const s=createGame('blocks',{seed:7});s.spawn=15;s.enemies=[];s.items=[{x:90,y:514,kind:'honey',ttl:12}];await open(page,s);await page.clock.runFor(50);await expect.poll(()=>page.evaluate(()=>window.stageClips.find(c=>c.src.includes('may-song'))?.audio.currentTime||0),{timeout:12000}).toBeGreaterThan(5);const clip=await page.evaluate(()=>{const a=window.stageClips.find(c=>c.src.includes('may-song')).audio;return {loop:a.loop,duration:a.duration};});expect(clip.loop).toBe(false);expect(clip.duration).toBeCloseTo(60,1);});
test('Byeol carry defeats a monster in another lane without attack input and survives reload',async({page},info)=>{const s=createGame('drive',{stage:3,seed:7});s.spawn=15;s.objects=[{id:0,lane:1,y:455,kind:'byeol'},{id:1,lane:0,y:300,kind:'monster',hp:2}];await open(page,s);await page.clock.runFor(50);await expect(page.locator('#app')).toHaveAttribute('data-byeol-carry','true');await expect(page.locator('#powerup-status')).toContainText('별이 캐리 20초');await page.clock.runFor(700);await expect(page.locator('#powerup-status')).toContainText('몬스터 1마리 격파');await page.screenshot({path:info.outputPath('byeol-carry.png'),fullPage:true});await page.locator('[data-pause]').click();const before=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).games.drive.snapshot,PROGRESS_KEY);expect(before.byeolTime).toBeGreaterThan(19);await page.reload();await page.locator('[data-start="drive"].start').click();await expect(page.locator('#app')).toHaveAttribute('data-state','paused');await page.locator('[data-resume]').click();await expect(page.locator('#app')).toHaveAttribute('data-byeol-carry','true');});
