import test from 'node:test';
import assert from 'node:assert/strict';
import {GAME_IDS,createGame,readRecords,saveRecord} from '../../src/arcade-room/model.js';
import {emptyProgress,readProgress,restoreRound,snapshotRound,saveProgress,PROGRESS_KEY} from '../../src/arcade-room/progress.js';
const storage=data=>({getItem:()=>JSON.stringify(data),setItem(){}});
test('legacy five-stage and old gameplay saves retain stages and lives but discard obsolete game boards',()=>{let p=readProgress(storage({version:1,games:{blocks:{cleared:[1,2,3,4,5]}}}));assert.equal(p.games.blocks.stage,6);const old=emptyProgress();old.games.blocks={stage:8,highest:10,hearts:2,snapshot:{kind:'blocks',stage:8,board:[]}};p=readProgress(storage(old));assert.deepEqual(p.games.blocks,{stage:8,highest:10,hearts:2,snapshot:null});});
test('new snapshots round-trip and corrupt or oversized saves fail safely',()=>{for(const kind of GAME_IDS){const s=snapshotRound(createGame(kind,{seed:7}));assert.ok(restoreRound(s));s.remaining=999;assert.equal(restoreRound(s),null);}assert.deepEqual(readProgress({getItem(){throw Error();}}),emptyProgress());assert.equal(saveProgress({setItem(){throw Error();}},emptyProgress()),false);assert.equal(typeof PROGRESS_KEY,'string');});
test('invalid game-specific structures cannot restore',()=>{for(const [kind,key,value] of [['drive','holes',[]],['blocks','player',null],['photo','board',[99]],['rhythm','notes',[]],['catch','gates',[{}]]]){const s=snapshotRound(createGame(kind));s[key]=value;assert.equal(restoreRound(s),null);}});
test('existing member records keep their stable game IDs',()=>{const records=readRecords(storage({drive:300,blocks:200,photo:100,rhythm:90,catch:70}));assert.equal(records.drive,300);let saved;saveRecord({getItem:()=>JSON.stringify(records),setItem:(key,value)=>saved=JSON.parse(value)},'photo',500);assert.equal(saved.photo,500);});
