/* global document, window, localStorage, requestAnimationFrame, performance */
import {createGame,stepGame,gameAction,readRecords,saveRecord,GAME_IDS,INITIAL_LIVES} from './model.js';
import {GAMES,REACTIONS,extraValue,resultLine,SIGNATURES} from './catalog.js';
import {loadCast,paintDolls} from './cast.js';
import {drawGame,targets,loadGameArt,PUMP_ARROWS} from './render.js';
import {ArcadeAudio} from './audio.js';
import {mountCarousel} from './carousel.js';
import {breadFrame} from './model.js';
import {TRACKS} from './music.js';
import {VOICES} from './voices.js';
import {readProgress,saveProgress,restoreRound,stageGoal,stageValue,isStageClear,finishStage,newRun,saveRound} from './progress.js';
let selectedGame='drive',disposePicker=()=>{},breadDrag=null;
const app=document.querySelector('#app'),audio=new ArcadeAudio();
let state,mode='loading',paused=false,last=0,storage,records=readRecords(),ready=false,held=null,reactions=0,offsetMs=0;
try{storage=localStorage;records=readRecords(storage);const n=Number(storage.getItem('rescene.rhythm.offset'));offsetMs=Number.isFinite(n)?Math.max(-200,Math.min(200,n)):0;}catch{/* Optional local storage. */}
let progress=readProgress(storage),saveOK=!!storage,savedAt=0,reactionUntil=0;
function persist(){
 if(state&&mode==='play'&&!state.ended)saveRound(progress,state);
 saveOK=saveProgress(storage,progress);savedAt=performance.now();
 const label=app.querySelector('#save-state');if(label)label.textContent=saveMessage();return saveOK;
}
function saveMessage(){return saveOK?'자동 저장 · 이 브라우저에서 이어하기':'저장할 수 없어 이번 탭에서만 이어갈 수 있어요.';}
function stagePicker(id){const entry=progress.games[id];return `<div class="journey-card" aria-label="${GAMES[id].name}의 도전"><b>STAGE ${entry.stage}</b><span>${entry.hearts?'♥'.repeat(entry.hearts)+'♡'.repeat(INITIAL_LIVES-entry.hearts):'도전 종료'}</span><small>최고 STAGE ${entry.highest} · 끝없이 도전</small></div>`;}
function celebrate(){
 const signature=SIGNATURES[GAMES[state.kind].member];decorate(3);reactionUntil=performance.now()+1100;
 const toast=app.querySelector('.signature-toast');toast.hidden=false;toast.dataset.pose=signature.motion;toast.querySelector('span').textContent=signature.label;
 if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){
  const frames=signature.motion==='dance'?[{transform:'rotate(-8deg)'},{transform:'translateY(-12px) rotate(8deg)'},{transform:'rotate(0deg)'}]:[{transform:'scale(.88)'},{transform:'scale(1.08) rotate(-4deg)'},{transform:'scale(1)'}];
  app.querySelectorAll('.companion .doll,.signature-toast .doll').forEach(c=>{c.getAnimations().forEach(a=>a.cancel());c.animate(frames,{duration:600,easing:'ease-out'});});
 }
}
function goalReached(){if(!(state.kind==='photo'&&state.flash)&&isStageClear(state))state.ended=true;}
function doll(id){return `<canvas class="doll" data-doll="${id}" role="img" aria-label="${Object.values(GAMES).find(g=>g.member===id).name} 캐릭터"></canvas>`;}
function header(play=false){return `<header class="topbar"><button class="brand" data-home aria-label="리센느 작은 오락실 홈"><span class="brand-mark">r.</span><span>리센느<small>작은 오락실</small></span></button>${play?'<button class="quiet" data-pause>잠깐 쉬기 Ⅱ</button>':'<span class="open-sign"><i></i> 다섯 친구가 기다려요</span>'}</header>`;}
function decorate(pose=0){if(ready)paintDolls(app,pose);}
function home(){
 disposePicker();breadDrag=null;
 if(mode==='play')persist();audio.stop();held=null;mode='home';state=null;paused=false;records=readRecords(storage);app.dataset.state='home';delete app.dataset.game;
 app.innerHTML=`${header()}<section class="welcome"><div><p class="hello">바닷가 작은 오락실에 오신 걸 환영해요</p><h1>잠깐, 한 판 할래?</h1><p>목숨 3개로 어디까지 갈 수 있을까? 스테이지는 끝없이, 멈춘 곳부터 다시 만나요.</p></div><span class="ticket">한 판의<br><b>작은 행복</b><span>✦ ✦ ✦</span></span></section><section class="game-picker" aria-roledescription="carousel" aria-label="멤버 게임 선택"><nav class="member-nav" aria-label="멤버 게임 바로가기">${Object.entries(GAMES).map(([id,g])=>`<button data-slide="${id}" aria-controls="machine-${id}">${g.name}</button>`).join('')}</nav><div class="picker-controls"><button data-slide-step="-1" aria-label="이전 게임">‹</button><p><strong data-slide-status role="status" aria-live="polite"></strong><small>좌우로 넘겨 골라요</small></p><button data-slide-step="1" aria-label="다음 게임">›</button></div><section class="machines" tabindex="0" aria-label="게임 목록 · 좌우 화살표로 선택">${Object.entries(GAMES).map(([id,g])=>`<article id="machine-${id}" class="machine ${g.color}" role="group" aria-roledescription="slide" aria-label="${g.name}의 ${g.title}"><div class="marquee"><span>${g.name}의</span><h2>${g.title}</h2><span class="machine-badge">무한 도전</span></div><div class="cabinet-screen"><div class="mini-scene ${id}"><canvas class="preview" data-preview="${id}" aria-hidden="true"></canvas></div><div class="host">${doll(g.member)}<span class="speech">${g.line}</span></div></div><div class="control-deck"><p>${g.hint}</p>${stagePicker(id)}<button class="start" data-start="${id}" aria-label="${g.name}의 ${g.title} 시작" ${ready?'':'disabled'}>${ready?(!progress.games[id].hearts?'새 도전':progress.games[id].snapshot||progress.games[id].stage>1||progress.games[id].hearts<INITIAL_LIVES?'이어서 하기':'바로 시작'):'캐릭터 준비 중'} <span>▶</span></button><div class="cabinet-bottom"><span class="speaker-grill"></span><small>내 최고 기록 <b>${records[id].toLocaleString()}</b></small><span class="coin-slot"></span></div></div></article>`).join('')}</section></section><footer>비공식 팬 게임 · 멤버의 공개된 취향에서 출발한 창작 오락실<br>진행 상황과 최고 기록은 이 브라우저에 저장돼요. 다른 기기와는 공유되지 않아요.<br>${saveMessage()}</footer>`;
 disposePicker=mountCarousel(app.querySelector('.game-picker'),selectedGame,id=>{selectedGame=id;});
 decorate();app.querySelectorAll('[data-preview]').forEach(c=>{c.width=480;c.height=600;const s=createGame(c.dataset.preview,{seed:17});s.preview=true;if(s.kind==='drive'){s.holes[1]={ttl:1,total:1.7,gold:false,flash:0};s.holes[5]={ttl:1,total:1.7,gold:true,flash:0};}if(s.kind==='catch'){s.squad=8;s.enemies=[{id:0,lane:1,y:140,hp:6,maxHp:6,boss:false}];}if(s.kind==='rhythm')s.elapsed=1;drawGame(c.getContext('2d'),s);});
}
function controls(kind){
 if(kind==='drive')return '<span class="tap-instruction">구멍을 직접 눌러요 · 1~9</span>';
 if(kind==='photo')return '<button data-act="shuffle" class="skill-button">빵 섞기 · 2회</button>';
 if(kind==='catch')return '<button data-act="left" aria-label="왼쪽 길로 이동">◀</button><button data-act="burst" class="skill-button">✦ 지원 0/5</button><button data-act="right" aria-label="오른쪽 길로 이동">▶</button>';
 if(kind==='rhythm')return `<div class="pump-pad">${PUMP_ARROWS.map((arrow,i)=>`<button data-act="${i}" class="pad-${i}" aria-label="${['왼쪽 아래','왼쪽 위','가운데','오른쪽 위','오른쪽 아래'][i]} 발판">${arrow}<small>${['Z','Q','S','E','C'][i]}</small></button>`).join('')}</div>`;
 return '<button data-act="left" aria-label="왼쪽으로 이동">◀</button><button data-act="right" aria-label="오른쪽으로 이동">▶</button><button data-act="turn" class="turn" aria-label="제자리 뒤돌기">뒤돌기</button><button data-act="jump" class="jump">점프 ↑</button><button data-act="bubble" class="bubble-button">방울 ○</button>';
}
function fieldControls(s){return `<div class="field-controls">${targets(s).map((t,i)=>`<button data-act="${i}" style="left:${t.x/4.8}%;top:${t.y/6}%;width:${t.w/4.8}%;height:${t.h/6}%" aria-label="${t.label}"></button>`).join('')}</div>`;}
function activateSound(){if(!audio.enabled)return;void audio.enable(true).then(()=>{const b=app.querySelector('[data-sound]');if(b){b.textContent=`소리 ${audio.enabled?'끄기':'켜기'}`;b.setAttribute('aria-pressed',String(audio.enabled));}});}
const inputAction=value=>/^\d+$/.test(value)?Number(value):value;
function start(kind,fresh=false){
 const g=GAMES[kind];if(!g||!ready)return;disposePicker();selectedGame=kind;breadDrag=null;const entry=progress.games[kind];if(fresh||entry.hearts===0)newRun(progress,kind);const resume=!fresh?restoreRound(entry.snapshot):null;audio.stop();held=null;mode='play';paused=false;reactions=0;reactionUntil=0;state=resume||createGame(kind,{offsetMs,stage:entry.stage,hearts:entry.hearts});app.dataset.game=kind;app.dataset.state='playing';delete app.dataset.cleared;
 app.innerHTML=`${header(true)}<section class="play-layout ${g.color}"><aside class="companion"><button class="text-back" data-home>‹ 오락실</button><p class="host-name">${g.name}와 함께</p><h1>${g.title}</h1>${doll(g.member)}<p class="host-line" id="reaction">${g.line}</p><p class="key-guide">${g.keys}</p></aside><div class="game-cabinet"><div class="stage-goal"><b>STAGE ${state.stage}</b><span id="lives" aria-label="남은 목숨 ${state.hearts}개">${'♥'.repeat(state.hearts)+'♡'.repeat(INITIAL_LIVES-state.hearts)}</span><span id="goal"></span></div><div class="scoreboard"><div><small>남은 시간</small><strong id="time">60<em>초</em></strong></div><div><small>점수</small><strong id="score">0</strong></div><div><small>${g.extra}</small><strong id="extra">${extraValue(state)}</strong></div></div><div class="playfield"><canvas id="game" width="480" height="600" tabindex="0" role="img" aria-label="${g.title} 게임 화면. ${g.hint}"></canvas>${fieldControls(state)}<div class="signature-toast" hidden aria-hidden="true">${doll(g.member)}<span></span></div><div id="overlay" hidden></div></div><div class="game-controls" aria-label="게임 조작">${controls(kind)}</div><p class="mobile-hint">${g.hint}</p></div><aside class="side-note"><p>내 최고 기록<strong id="best">${records[kind].toLocaleString()}</strong></p><div class="utility-buttons"><button class="quiet" data-help>하는 방법</button><button class="quiet" data-sound aria-pressed="${audio.enabled}">소리 ${audio.enabled?'끄기':'켜기'}</button><button class="quiet" data-music aria-pressed="${audio.musicEnabled}">BGM ${audio.musicEnabled?'끄기':'켜기'}</button><button class="quiet" data-voice aria-pressed="${audio.voiceEnabled}">멤버 음성 ${audio.voiceEnabled?'끄기':'켜기'}</button></div><small id="voice-preview-status" role="status">멤버 음성은 클리어 때 나와요 · 기본 켜짐</small><p id="save-state" role="status">${saveMessage()}</p><small class="music-credit">♪ ${TRACKS[kind].title} · ${TRACKS[kind].bpm} BPM<br>게임 전용 오리지널 연주곡</small><p class="short-guide">${g.guide}</p>${kind==='rhythm'?'<small>음악의 박자에 맞춰 발판을 눌러요.<br>판정 보정은 ‘하는 방법’에서 조절해요.</small>':''}</aside></section><p class="sr-only" id="announce" role="status"></p>`;
 decorate();draw();last=performance.now();app.querySelector('#game').focus({preventScroll:true});window.scrollTo(0,0);persist();if(resume){paused=true;setPaused(true);}activateSound();
}
function react(){
 if(!state.event)return;const event=state.event;state.event=null;const lines=REACTIONS[event];if(!lines)return;
 const line=lines[reactions++%lines.length];app.querySelector('#reaction').textContent=line;app.querySelector('#announce').textContent=line;const positive=!/miss|bump|early|invalid/.test(event);if(positive&&event!=='place')celebrate();else if(!positive)decorate(2);if(positive&&event!=='place'&&state.kind!=='rhythm')audio.tone(720);
}
function advanceTo(now){
 if(mode==='play'&&!paused){let remaining=Math.max(0,(now-last)/1000);while(remaining>0&&!state.ended){const dt=Math.min(.05,remaining);stepGame(state,dt);remaining-=dt;react();goalReached();if(held&&!state.ended){held.wait-=dt;if(held.wait<=0){gameAction(state,held.action);held.wait+=.085;react();goalReached();}}}if(state.ended)finish();}last=now;
}
function act(action){if(mode!=='play'||paused)return;advanceTo(performance.now());if(state.ended)return;if(action==='turn')held=null;gameAction(state,action);react();goalReached();draw();if(state.ended)finish();}
function draw(){if(mode!=='play')return;drawGame(app.querySelector('#game').getContext('2d'),state);app.querySelector('#score').textContent=state.score.toLocaleString();app.querySelector('#time').innerHTML=`${Math.ceil(state.remaining)}<em>초</em>`;app.querySelector('#extra').textContent=extraValue(state);const lives=app.querySelector('#lives');lives.textContent='♥'.repeat(state.hearts)+'♡'.repeat(INITIAL_LIVES-state.hearts);lives.setAttribute('aria-label',`남은 목숨 ${state.hearts}개`);const goal=stageGoal(state.kind,state.stage);app.querySelector('#goal').textContent=`${Math.min(stageValue(state),goal.target)} / ${goal.target} ${goal.unit}`;syncControls();}
function syncControls(){
 if(state.kind==='photo')app.dataset.breadPhase=breadFrame(state)?.kind||'idle';
 const buttons=app.querySelectorAll('.field-controls button');
 buttons.forEach((b,i)=>{if(state.kind==='drive'){const active=state.holes[i].ttl>0;b.dataset.active=String(active);b.setAttribute('aria-label',`${i+1}번 파이리 구멍${active?' · 파이리 나타남':''}`);}if(state.kind==='photo')b.setAttribute('aria-pressed',String(state.selected===i));if(state.kind==='catch'){b.setAttribute('aria-label',`${i+1}번 길로 이동`);b.setAttribute('aria-pressed',String(state.lane===i));}});
 const skill=app.querySelector('.skill-button');if(skill&&state.kind==='photo'){skill.textContent=`빵 섞기 · ${state.shuffles}회`;skill.disabled=state.shuffles===0||state.ended;}if(skill&&state.kind==='catch'){skill.textContent=state.charge===5?'✦ 별빛 지원':`✦ 지원 ${state.charge}/5`;skill.disabled=state.charge<5||state.ended;}
 if(state.kind==='rhythm')app.querySelectorAll('.pump-pad button').forEach((b,i)=>b.classList.toggle('lit',state.glows[i]>0));
}
function setPaused(value,help=false){
 if(mode!=='play'||state.ended)return;if(value){advanceTo(performance.now());if(state.ended)return;}paused=value;held=null;breadDrag=null;if(state.kind==='blocks')gameAction(state,'stop');audio.stop();last=performance.now();app.dataset.state=value?'paused':'playing';const overlay=app.querySelector('#overlay');overlay.hidden=!value;
 if(value){persist();const g=GAMES[state.kind];overlay.innerHTML=`<div class="pause-paper" role="dialog" aria-modal="true" aria-labelledby="pause-title"><h2 id="pause-title">${help?'이렇게 놀아요':'잠깐 쉬어가요'}</h2><p>${help?g.guide:'시간도 함께 멈췄어요.'}</p>${help?`<p class="dialog-keys">${g.keys}</p>`:''}${help&&state.kind==='rhythm'?`<label class="calibration">판정 보정 <output id="offset-value">${offsetMs}ms</output><input id="offset" type="range" min="-200" max="200" step="10" value="${offsetMs}"><small>소리보다 늦게 누르게 되면 + 쪽으로 조절해요.</small></label>`:''}<button class="start" data-resume>계속하기 ▶</button><button class="quiet" data-restart>스테이지 1부터 새 도전</button><button class="quiet" data-leave>오락실로 돌아가기</button><small>${saveMessage()}<br>새 도전은 스테이지 1, 목숨 3개로 시작해요. 최고 기록은 유지돼요.</small></div>`;overlay.querySelector('[data-resume]').focus();}else{app.querySelector('#game').focus({preventScroll:true});activateSound();}
}
function finish(){
 if(mode!=='play')return;held=null;audio.stop();const previous=records[state.kind],saved=saveRecord(storage,state.kind,state.score);records=saved.records;const cleared=finishStage(progress,state);persist();draw();mode='result';paused=false;app.dataset.state='result';app.dataset.cleared=String(cleared);
 const g=GAMES[state.kind],signature=SIGNATURES[g.member],voice=VOICES[g.member],next=GAME_IDS[(GAME_IDS.indexOf(state.kind)+1)%GAME_IDS.length],overlay=app.querySelector('#overlay');overlay.hidden=false;app.querySelector('.signature-toast').hidden=true;
 overlay.innerHTML=`<div class="result-paper" role="dialog" aria-modal="true" aria-labelledby="result-title"><p id="result-title">${cleared?`스테이지 ${state.stage} 클리어!`:state.hearts?'목숨이 남아 있어요!':'GAME OVER'}</p>${cleared?`<div class="clear-portrait">${doll(g.member)}</div>`:''}<h2>${state.score.toLocaleString()}<small>점</small></h2><p>${resultLine(state)}${state.score>previous?' · 새 최고 기록!':''}</p><p class="result-message">${cleared?signature.line:state.hearts?`${state.endReason==='timeout'?'시간 초과':state.endReason==='moves'?'교환 횟수를 다 썼어요':'다음 도전을 준비해요'} · 목숨 하나로 다시 도전해요.`:`스테이지 ${state.stage}까지 함께했어요!`}</p>${cleared?`<div class="member-voice"><small>${signature.adapted?'위 멘트는 게임용 각색 · ':''}원본 음성: “${voice.spoken}”</small><button class="voice-replay" data-speak>▶ ${g.name} 실제 음성 듣기</button><button class="voice-replay" data-stop-voice>음성 정지</button><a href="${voice.source}" target="_blank" rel="noopener noreferrer" aria-label="${g.name} 음성 출처 · 새 탭">출처 영상 ↗</a><small id="voice-status" role="status">원본 음성 · 방송 배경음 포함</small></div>`:''}<p class="result-lives">남은 목숨 ${'♥'.repeat(state.hearts)+'♡'.repeat(INITIAL_LIVES-state.hearts)}${cleared?' · 다음 스테이지에서 계속':''}</p><button class="start" data-start="${state.kind}">${cleared?'다음 스테이지 ▶':state.hearts?'다시 도전 ▶':'새 도전 ▶'}</button><button class="quiet" data-start="${next}">${GAMES[next].name}와도 놀기</button><button class="result-home" data-leave>오락실로</button><small>${saveOK&&saved.saved?'진행 상황과 최고 기록은 이 기기에 저장했어요.':'기기에 저장할 수 없어요. 이번 탭에서만 진행을 유지해요.'}</small></div>`;
 app.querySelector('#best').textContent=records[state.kind].toLocaleString();app.querySelector('[data-pause]').hidden=true;app.querySelectorAll('[data-act]').forEach(b=>b.disabled=true);decorate(cleared?3:0);app.querySelector('#announce').textContent=`${cleared?'스테이지 클리어':'게임 완료'}. ${state.score}점.`;overlay.querySelector('[data-start]').focus();if(cleared&&audio.voiceEnabled)speakClear();
}
function speakClear(){const label=app.querySelector('#voice-status');audio.playVoice(VOICES[GAMES[state.kind].member],message=>{if(label?.isConnected)label.textContent=message;});}
app.addEventListener('click',async e=>{
 const b=e.target.closest('button');if(!b)return;if(b.dataset.start)start(b.dataset.start);else if(b.hasAttribute('data-restart'))start(state.kind,true);else if(b.hasAttribute('data-voice')){audio.voiceEnabled=!audio.voiceEnabled;if(!audio.voiceEnabled)audio.cancelVoice();else{const label=app.querySelector('#voice-preview-status');audio.playVoice(VOICES[GAMES[state.kind].member],message=>{if(label?.isConnected)label.textContent=message;});}b.textContent=`멤버 음성 ${audio.voiceEnabled?'끄기':'켜기'}`;b.setAttribute('aria-pressed',String(audio.voiceEnabled));}else if(b.hasAttribute('data-speak'))speakClear();else if(b.hasAttribute('data-stop-voice'))audio.cancelVoice();else if(b.hasAttribute('data-act')&&e.detail===0)act(inputAction(b.dataset.act));else if(b.hasAttribute('data-pause'))setPaused(!paused);else if(b.hasAttribute('data-help'))setPaused(true,true);else if(b.hasAttribute('data-resume'))setPaused(false);else if(b.hasAttribute('data-leave')){home();window.scrollTo(0,0);}else if(b.hasAttribute('data-home')){if(mode==='play')setPaused(true);else{home();window.scrollTo(0,0);}}else if(b.hasAttribute('data-music')){audio.setMusic(!audio.musicEnabled);b.textContent=`BGM ${audio.musicEnabled?'끄기':'켜기'}`;b.setAttribute('aria-pressed',String(audio.musicEnabled));}else if(b.hasAttribute('data-sound')){const enabled=await audio.enable(!audio.enabled);if(b.isConnected){b.textContent=enabled?'소리 끄기':'소리 켜기';b.setAttribute('aria-pressed',String(enabled));}if(enabled)audio.tone();}
});
app.addEventListener('input',e=>{if(e.target.id==='offset'){offsetMs=Number(e.target.value);state.offset=offsetMs/1000;app.querySelector('#offset-value').textContent=`${offsetMs}ms`;try{storage?.setItem('rescene.rhythm.offset',String(offsetMs));}catch{/* Optional preference. */}}});
app.addEventListener('pointerdown',e=>{if(mode!=='play'||paused||state.ended)return;const b=e.target.closest('[data-act]');if(b&&!b.disabled){if(state.kind==='photo'&&b.closest('.field-controls')){if(breadDrag||!e.isPrimary||state.flash)return;e.preventDefault();b.setPointerCapture(e.pointerId);breadDrag={id:e.pointerId,index:Number(b.dataset.act),x:e.clientX,y:e.clientY,size:b.getBoundingClientRect().width};return;}e.preventDefault();b.setPointerCapture(e.pointerId);const action=inputAction(b.dataset.act);act(action);if(state.kind==='blocks'&&['left','right'].includes(action))held={action,wait:.08,pointerId:e.pointerId};}});
app.addEventListener('pointerup',e=>{
 if(!breadDrag||breadDrag.id!==e.pointerId)return;const d=breadDrag;breadDrag=null;
 if(mode!=='play'||paused||state.kind!=='photo')return;
 const dx=e.clientX-d.x,dy=e.clientY-d.y,ax=Math.abs(dx),ay=Math.abs(dy),threshold=Math.max(10,d.size*.22);
 if(Math.max(ax,ay)<threshold){act(d.index);return;}
 if(Math.max(ax,ay)<Math.min(ax,ay)*1.2)return;
 const horizontal=ax>ay,step=horizontal?Math.sign(dx):Math.sign(dy)*6,to=d.index+step;
 if(to<0||to>=36||horizontal&&Math.floor(to/6)!==Math.floor(d.index/6))return;
 act({from:d.index,to});
});
for(const type of ['pointercancel','lostpointercapture'])app.addEventListener(type,e=>{if(breadDrag?.id===e.pointerId)breadDrag=null;});
function releaseMovement(e){if(e?.type==='keyup'){if(held?.pointerId!==undefined||held?.action!==({ArrowLeft:'left',ArrowRight:'right'}[e.key]))return;}else if(held?.pointerId!==e?.pointerId)return;held=null;if(mode==='play'&&state.kind==='blocks')gameAction(state,'stop');}
for(const type of ['pointerup','pointercancel','lostpointercapture'])app.addEventListener(type,releaseMovement);
window.addEventListener('keyup',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key))releaseMovement(e);});
window.addEventListener('keydown',e=>{
 if(mode==='home')return;const overlay=app.querySelector('#overlay');if(e.key==='Tab'&&overlay&&!overlay.hidden){const nodes=[...overlay.querySelectorAll('button:not(:disabled),input:not(:disabled),a[href]')],index=nodes.indexOf(document.activeElement);if(nodes.length){e.preventDefault();nodes[(index+(e.shiftKey?-1:1)+nodes.length)%nodes.length].focus();}return;}
 if(mode!=='play')return;if(e.key==='Escape'){e.preventDefault();setPaused(!paused);return;}if(paused)return;if(['BUTTON','INPUT','A'].includes(e.target.tagName)&&(e.key===' '||e.key==='Enter'))return;
 if(state.kind==='photo'&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const buttons=[...app.querySelectorAll('.field-controls button')],from=Math.max(0,buttons.indexOf(document.activeElement)),delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-6,ArrowDown:6}[e.key];buttons[Math.max(0,Math.min(35,from+delta))].focus();return;}
 const map=state.kind==='rhythm'?{z:0,Z:0,q:1,Q:1,s:2,S:2,e:3,E:3,c:4,C:4}:state.kind==='blocks'?{ArrowLeft:'left',ArrowRight:'right',' ':'jump',f:'bubble',F:'bubble',x:'turn',X:'turn'}:state.kind==='catch'?{ArrowLeft:'left',ArrowRight:'right',' ':'burst'}:{};
 let action=map[e.key];if(state.kind==='drive'&&/^[1-9]$/.test(e.key))action=Number(e.key)-1;if(state.kind==='catch'&&/^[1-3]$/.test(e.key))action=Number(e.key)-1;
 if(action!==undefined){e.preventDefault();if(!e.repeat||(state.kind==='blocks'&&action!=='turn'))act(action);if(state.kind==='blocks'&&['left','right'].includes(action))held={action,wait:.08};}

});
document.addEventListener('visibilitychange',()=>{if(document.hidden){audio.stop();setPaused(true);}});window.addEventListener('blur',()=>{audio.stop();setPaused(true);});window.addEventListener('pagehide',()=>{audio.stop();if(mode==='play'){setPaused(true);persist();}});
function frame(now){advanceTo(now);if(mode==='play'&&!paused){audio.tick(state);draw();if(now-savedAt>1000)persist();if(reactionUntil&&now>reactionUntil){reactionUntil=0;decorate();app.querySelector('.signature-toast').hidden=true;}}requestAnimationFrame(frame);}
home();requestAnimationFrame(frame);Promise.all([loadCast(),loadGameArt()]).then(()=>{ready=true;home();}).catch(()=>{app.querySelector('.welcome').insertAdjacentHTML('beforeend','<p role="alert">캐릭터를 불러오지 못했어요. 페이지를 새로고침해 주세요.</p>');});
