/* global document, window, localStorage, requestAnimationFrame, performance */
import {createGame,stepGame,gameAction,readRecords,saveRecord,GAME_IDS,STAGE_COUNT} from './model.js';
import {GAMES,REACTIONS,extraValue,resultLine,SIGNATURES} from './catalog.js';
import {loadCast,paintDolls} from './cast.js';
import {drawGame,drawNext} from './render.js';
import {ArcadeAudio} from './audio.js';
import {readProgress,saveProgress,snapshotRound,restoreRound,stageGoal,stageValue,isStageClear,finishStage} from './progress.js';
const app=document.querySelector('#app'),audio=new ArcadeAudio();
let state,mode='loading',paused=false,last=0,storage,records=readRecords(),ready=false,held=null,reactions=0,offsetMs=0;
try{storage=localStorage;records=readRecords(storage);const n=Number(storage.getItem('rescene.rhythm.offset'));offsetMs=Number.isFinite(n)?Math.max(-200,Math.min(200,n)):0;}catch{/* Optional local storage. */}
let progress=readProgress(storage),saveOK=!!storage,savedAt=0,reactionUntil=0;
function persist(){
 if(state&&mode==='play'&&!state.ended)progress.games[state.kind].snapshot=snapshotRound(state);
 saveOK=saveProgress(storage,progress);savedAt=performance.now();
 const label=app.querySelector('#save-state');if(label)label.textContent=saveMessage();return saveOK;
}
function saveMessage(){return saveOK?'자동 저장 · 이 브라우저에서 이어하기':'저장할 수 없어 이번 탭에서만 이어갈 수 있어요.';}
function stagePicker(id){const entry=progress.games[id];return `<div class="stage-path" aria-label="${GAMES[id].name}의 스테이지">${Array.from({length:STAGE_COUNT},(_,i)=>`<button data-start="${id}" data-stage="${i+1}" aria-label="${GAMES[id].name} 스테이지 ${i+1}${entry.cleared.includes(i+1)?' 완료':''}" ${!ready||i+1>entry.unlocked||entry.snapshot?'disabled':''} class="${entry.cleared.includes(i+1)?'cleared':''}">${entry.cleared.includes(i+1)?'✓':i+1}</button>`).join('')}<small>${entry.cleared.length===STAGE_COUNT?'모두 클리어!':`${entry.cleared.length} / ${STAGE_COUNT} 완료`}</small></div>`;}
function celebrate(){
 const signature=SIGNATURES[GAMES[state.kind].member];decorate(3);reactionUntil=performance.now()+1100;
 const toast=app.querySelector('.signature-toast');toast.hidden=false;toast.dataset.pose=signature.motion;toast.querySelector('span').textContent=signature.label;
 if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){
  const frames=signature.motion==='dance'?[{transform:'rotate(-8deg)'},{transform:'translateY(-12px) rotate(8deg)'},{transform:'rotate(0deg)'}]:[{transform:'scale(.88)'},{transform:'scale(1.08) rotate(-4deg)'},{transform:'scale(1)'}];
  app.querySelectorAll('.companion .doll,.signature-toast .doll').forEach(c=>{c.getAnimations().forEach(a=>a.cancel());c.animate(frames,{duration:600,easing:'ease-out'});});
 }
}
function goalReached(){if(isStageClear(state))state.ended=true;}
function doll(id){return `<canvas class="doll" data-doll="${id}" role="img" aria-label="${Object.values(GAMES).find(g=>g.member===id).name} 캐릭터"></canvas>`;}
function header(play=false){return `<header class="topbar"><button class="brand" data-home aria-label="리센느 작은 오락실 홈"><span class="brand-mark">r.</span><span>리센느<small>작은 오락실</small></span></button>${play?'<button class="quiet" data-pause>잠깐 쉬기 Ⅱ</button>':'<span class="open-sign"><i></i> 다섯 친구가 기다려요</span>'}</header>`;}
function decorate(pose=0){if(ready)paintDolls(app,pose);}
function home(){
 if(mode==='play')persist();audio.stop();held=null;mode='home';state=null;paused=false;records=readRecords(storage);app.dataset.state='home';delete app.dataset.game;
 app.innerHTML=`${header()}<section class="welcome"><div><p class="hello">바닷가 작은 오락실에 오신 걸 환영해요</p><h1>잠깐, 한 판 할래?</h1><p>한 판은 60초. 다섯 스테이지를 차곡차곡, 멈춘 곳부터 다시 만나요.</p></div><span class="ticket">한 판의<br><b>작은 행복</b><span>✦ ✦ ✦</span></span></section><nav class="member-nav" aria-label="멤버 게임 바로가기">${Object.entries(GAMES).map(([id,g])=>`<a href="#machine-${id}">${g.name}</a>`).join('')}</nav><section class="machines" aria-label="다섯 멤버의 게임">${Object.entries(GAMES).map(([id,g])=>`<article id="machine-${id}" class="machine ${g.color}"><div class="marquee"><span>${g.name}의</span><h2>${g.title}</h2><span class="machine-badge">60초</span></div><div class="cabinet-screen"><div class="mini-scene ${id}"><canvas class="preview" data-preview="${id}" aria-hidden="true"></canvas></div><div class="host">${doll(g.member)}<span class="speech">${g.line}</span></div></div><div class="control-deck"><p>${g.hint}</p>${stagePicker(id)}<button class="start" data-start="${id}" aria-label="${g.name}의 ${g.title} 시작" ${ready?'':'disabled'}>${ready?(progress.games[id].snapshot?'이어서 하기':'바로 시작'):'캐릭터 준비 중'} <span>▶</span></button><div class="cabinet-bottom"><span class="speaker-grill"></span><small>내 최고 기록 <b>${records[id].toLocaleString()}</b></small><span class="coin-slot"></span></div></div></article>`).join('')}</section><footer>비공식 팬 게임 · 멤버의 공개된 취향에서 출발한 창작 오락실<br>진행 상황과 최고 기록은 이 브라우저에 저장돼요. 다른 기기와는 공유되지 않아요.<br>${saveMessage()}</footer>`;
 decorate();app.querySelectorAll('[data-preview]').forEach(c=>{c.width=480;c.height=600;const s=createGame(c.dataset.preview);s.preview=true;if(s.kind==='drive'){s.elapsed=5;s.objects=[{lane:0,y:.23,kind:'star'},{lane:2,y:.45,kind:'cone'}];}if(s.kind==='blocks')s.board[11]=[1,1,0,0,2,2,3,3];if(s.kind==='rhythm')s.elapsed=3;if(s.kind==='catch')s.objects=[{lane:0,y:.25,blue:false},{lane:2,y:.4,blue:true}];drawGame(c.getContext('2d'),s);});
}
function controls(kind){
 if(kind==='photo')return '<button data-act="snap" class="shutter" aria-label="사진 찍기">◎ 찰칵!</button>';
 return `<button data-act="left" aria-label="${kind==='rhythm'?'왼쪽 박자':'왼쪽으로 이동'}">◀</button>${kind==='blocks'?'<button data-act="rotate" aria-label="조각 회전">↻<small>회전</small></button>':''}<button data-act="right" aria-label="${kind==='rhythm'?'오른쪽 박자':'오른쪽으로 이동'}">▶</button>${kind==='blocks'?'<button class="drop" data-act="drop">내려놓기 ↓</button>':''}`;
}
function start(kind,requestedStage, fresh=false){
 const g=GAMES[kind];if(!g||!ready)return;const entry=progress.games[kind],stage=requestedStage||entry.unlocked;if(!Number.isInteger(stage)||stage<1||stage>entry.unlocked)return;const resume=!fresh&&!requestedStage?restoreRound(entry.snapshot):null;audio.stop();held=null;mode='play';paused=false;reactions=0;reactionUntil=0;state=resume||createGame(kind,{offsetMs,stage});app.dataset.game=kind;app.dataset.state='playing';delete app.dataset.cleared;
 app.innerHTML=`${header(true)}<section class="play-layout ${g.color}"><aside class="companion"><button class="text-back" data-home>‹ 오락실</button><p class="host-name">${g.name}와 함께</p><h1>${g.title}</h1>${doll(g.member)}<p class="host-line" id="reaction">${g.line}</p><p class="key-guide">${g.keys}</p></aside><div class="game-cabinet"><div class="stage-goal"><b>STAGE ${state.stage} / ${STAGE_COUNT}</b><span id="goal"></span></div><div class="scoreboard"><div><small>남은 시간</small><strong id="time">60<em>초</em></strong></div><div><small>점수</small><strong id="score">0</strong></div><div><small>${g.extra}</small><strong id="extra">${extraValue(state)}</strong></div></div>${kind==='blocks'?'<div class="next-piece"><span>다음 조각</span><canvas id="next" width="160" height="80" role="img" aria-label="다음에 나올 조각"></canvas><small>점선은 놓일 자리</small></div>':''}<div class="playfield"><canvas id="game" width="480" height="600" tabindex="0" role="img" aria-label="${g.title} 게임 화면. ${g.hint}"></canvas><div class="signature-toast" hidden aria-hidden="true">${doll(g.member)}<span></span></div><div id="overlay" hidden></div></div><div class="game-controls" aria-label="게임 조작">${controls(kind)}</div><p class="mobile-hint">${g.hint}</p></div><aside class="side-note"><p>내 최고 기록<strong id="best">${records[kind].toLocaleString()}</strong></p><div class="utility-buttons"><button class="quiet" data-help>하는 방법</button><button class="quiet" data-sound aria-pressed="${audio.enabled}">소리 ${audio.enabled?'끄기':'켜기'}</button><button class="quiet" data-voice aria-pressed="${audio.voiceEnabled}">합성 음성 ${audio.voiceEnabled?'끄기':'켜기'}</button></div><small>임시 합성 음성 · 실제 멤버 녹음 아님</small><p id="save-state" role="status">${saveMessage()}</p><p class="short-guide">${g.guide}</p>${kind==='rhythm'?'<small>소리를 켜면 직접 만든 박자가 들려요.<br>판정 보정은 ‘하는 방법’에서 조절해요.</small>':''}</aside></section><p class="sr-only" id="announce" role="status"></p>`;
 decorate();draw();last=performance.now();app.querySelector('#game').focus({preventScroll:true});window.scrollTo(0,0);persist();if(resume){paused=true;setPaused(true);}
}
function react(){
 if(!state.event)return;const event=state.event;state.event=null;const lines=REACTIONS[event];if(!lines)return;
 const line=lines[reactions++%lines.length];app.querySelector('#reaction').textContent=line;app.querySelector('#announce').textContent=line;const positive=!/miss|bump|early/.test(event);if(positive&&event!=='place')celebrate();else if(!positive)decorate(2);if(positive&&event!=='place')audio.tone(state.kind==='rhythm'?880:720);
}
function advanceTo(now){
 if(mode==='play'&&!paused){let remaining=Math.max(0,(now-last)/1000);while(remaining>0&&!state.ended){const dt=Math.min(.05,remaining);stepGame(state,dt);remaining-=dt;react();goalReached();if(held&&!state.ended){held.wait-=dt;if(held.wait<=0){gameAction(state,held.action);held.wait+=.085;react();goalReached();}}}if(state.ended)finish();}last=now;
}
function act(action){if(mode!=='play'||paused)return;advanceTo(performance.now());if(state.ended)return;gameAction(state,action);react();goalReached();draw();if(state.ended)finish();}
function draw(){if(mode!=='play')return;drawGame(app.querySelector('#game').getContext('2d'),state);if(state.kind==='blocks')drawNext(app.querySelector('#next').getContext('2d'),state.next);app.querySelector('#score').textContent=state.score.toLocaleString();app.querySelector('#time').innerHTML=`${Math.ceil(state.remaining)}<em>초</em>`;app.querySelector('#extra').textContent=extraValue(state);const goal=stageGoal(state.kind,state.stage);app.querySelector('#goal').textContent=`${Math.min(stageValue(state),goal.target)} / ${goal.target} ${goal.unit}`;}
function setPaused(value,help=false){
 if(mode!=='play'||state.ended)return;if(value){advanceTo(performance.now());if(state.ended)return;}paused=value;held=null;audio.stop();last=performance.now();app.dataset.state=value?'paused':'playing';const overlay=app.querySelector('#overlay');overlay.hidden=!value;
 if(value){persist();const g=GAMES[state.kind];overlay.innerHTML=`<div class="pause-paper" role="dialog" aria-modal="true" aria-labelledby="pause-title"><h2 id="pause-title">${help?'이렇게 놀아요':'잠깐 쉬어가요'}</h2><p>${help?g.guide:'시간도 함께 멈췄어요.'}</p>${help?`<p class="dialog-keys">${g.keys}</p>`:''}${help&&state.kind==='rhythm'?`<label class="calibration">판정 보정 <output id="offset-value">${offsetMs}ms</output><input id="offset" type="range" min="-200" max="200" step="10" value="${offsetMs}"><small>소리보다 늦게 누르게 되면 + 쪽으로 조절해요.</small></label>`:''}<button class="start" data-resume>계속하기 ▶</button><button class="quiet" data-restart>이번 스테이지 다시 시작</button><button class="quiet" data-leave>오락실로 돌아가기</button><small>${saveMessage()}<br>다시 시작하면 이번 판의 진행만 초기화돼요.</small></div>`;overlay.querySelector('[data-resume]').focus();}else app.querySelector('#game').focus({preventScroll:true});
}
function finish(){
 if(mode!=='play')return;held=null;audio.stop();const previous=records[state.kind],saved=saveRecord(storage,state.kind,state.score);records=saved.records;const cleared=finishStage(progress,state);persist();draw();mode='result';paused=false;app.dataset.state='result';app.dataset.cleared=String(cleared);
 const g=GAMES[state.kind],signature=SIGNATURES[g.member],next=GAME_IDS[(GAME_IDS.indexOf(state.kind)+1)%GAME_IDS.length],overlay=app.querySelector('#overlay');overlay.hidden=false;app.querySelector('.signature-toast').hidden=true;
 overlay.innerHTML=`<div class="result-paper" role="dialog" aria-modal="true" aria-labelledby="result-title"><p id="result-title">${cleared?(state.stage===STAGE_COUNT?'다섯 스테이지 모두 클리어!':`스테이지 ${state.stage} 클리어!`):'조금만 더, 다시 도전!'}</p>${cleared?`<div class="clear-portrait">${doll(g.member)}</div>`:''}<h2>${state.score.toLocaleString()}<small>점</small></h2><p>${resultLine(state)}${state.score>previous?' · 새 최고 기록!':''}</p><p class="result-message">${cleared?signature.line:`목표 ${stageGoal(state.kind,state.stage).target}${stageGoal(state.kind,state.stage).unit}에 다시 도전해요.`}</p>${cleared?'<button class="voice-replay" data-speak>▶ 클리어 멘트 듣기 · 합성 음성</button><small id="voice-status" role="status"></small>':''}${cleared&&state.stage<STAGE_COUNT?`<button class="start" data-start="${state.kind}" data-stage="${state.stage+1}">다음 스테이지 ▶</button>`:''}<button class="${cleared&&state.stage<STAGE_COUNT?'quiet':'start'}" data-start="${state.kind}" data-stage="${state.stage}">한 판 더 ▶</button><button class="quiet" data-start="${next}">${GAMES[next].name}와도 놀기</button><button class="result-home" data-leave>오락실로</button><small>${saveOK&&saved.saved?'진행 상황과 최고 기록은 이 기기에 저장했어요.':'기기에 저장할 수 없어요. 이번 탭에서만 진행을 유지해요.'}</small></div>`;
 app.querySelector('#best').textContent=records[state.kind].toLocaleString();app.querySelector('[data-pause]').hidden=true;app.querySelectorAll('[data-act]').forEach(b=>b.disabled=true);decorate(cleared?3:0);app.querySelector('#announce').textContent=`${cleared?'스테이지 클리어':'게임 완료'}. ${state.score}점.`;overlay.querySelector('[data-start]').focus();if(cleared&&audio.voiceEnabled)speakClear();
}
function speakClear(){const label=app.querySelector('#voice-status');audio.speak(SIGNATURES[GAMES[state.kind].member].line,message=>{if(label?.isConnected)label.textContent=message;});}
app.addEventListener('click',async e=>{
 const b=e.target.closest('button');if(!b)return;if(b.dataset.start)start(b.dataset.start,b.dataset.stage?Number(b.dataset.stage):undefined);else if(b.hasAttribute('data-restart'))start(state.kind,state.stage,true);else if(b.hasAttribute('data-voice')){audio.voiceEnabled=!audio.voiceEnabled;if(!audio.voiceEnabled)audio.cancelVoice();b.textContent=`합성 음성 ${audio.voiceEnabled?'끄기':'켜기'}`;b.setAttribute('aria-pressed',String(audio.voiceEnabled));}else if(b.hasAttribute('data-speak'))speakClear();else if(b.dataset.act&&e.detail===0)act(b.dataset.act);else if(b.hasAttribute('data-pause'))setPaused(!paused);else if(b.hasAttribute('data-help'))setPaused(true,true);else if(b.hasAttribute('data-resume'))setPaused(false);else if(b.hasAttribute('data-leave')){home();window.scrollTo(0,0);}else if(b.hasAttribute('data-home')){if(mode==='play')setPaused(true);else{home();window.scrollTo(0,0);}}else if(b.hasAttribute('data-sound')){const enabled=await audio.enable(!audio.enabled);if(b.isConnected){b.textContent=enabled?'소리 끄기':'소리 켜기';b.setAttribute('aria-pressed',String(enabled));}if(enabled)audio.tone();}
});
app.addEventListener('input',e=>{if(e.target.id==='offset'){offsetMs=Number(e.target.value);state.offset=offsetMs/1000;app.querySelector('#offset-value').textContent=`${offsetMs}ms`;try{storage?.setItem('rescene.rhythm.offset',String(offsetMs));}catch{/* Optional preference. */}}});
function pointLane(e){const rect=e.target.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*480;state.lane=Math.max(0,Math.min(2,Math.floor(state.kind==='drive'?(x-105)/90:(x-52.5)/125)));draw();}
app.addEventListener('pointerdown',e=>{if(mode!=='play'||paused||state.ended)return;const b=e.target.closest('[data-act]');if(b){e.preventDefault();b.setPointerCapture(e.pointerId);act(b.dataset.act);if(state.kind==='blocks'&&['left','right'].includes(b.dataset.act))held={action:b.dataset.act,wait:.28};}else if(e.target.id==='game'&&['drive','catch'].includes(state.kind)){e.preventDefault();e.target.setPointerCapture(e.pointerId);pointLane(e);}});
app.addEventListener('pointermove',e=>{if(e.target.id==='game'&&e.buttons&&mode==='play'&&!paused&&!state.ended&&['drive','catch'].includes(state.kind))pointLane(e);});
for(const type of ['pointerup','pointercancel','lostpointercapture'])app.addEventListener(type,()=>{held=null;});
window.addEventListener('keydown',e=>{
 if(mode==='home')return;const overlay=app.querySelector('#overlay');if(e.key==='Tab'&&overlay&&!overlay.hidden){const nodes=[...overlay.querySelectorAll('button,input')],first=nodes[0],end=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first.focus();}return;}
 if(mode!=='play')return;if(e.key==='Escape'){e.preventDefault();setPaused(!paused);return;}if(paused)return;if(['BUTTON','INPUT','A'].includes(e.target.tagName)&&(e.key===' '||e.key==='Enter'))return;
 const map=state.kind==='photo'?{' ':'snap',Enter:'snap'}:state.kind==='rhythm'?{ArrowLeft:'left',ArrowRight:'right',a:'left',A:'left',l:'right',L:'right'}:{ArrowLeft:'left',ArrowRight:'right',ArrowUp:'rotate',ArrowDown:'down',' ':'drop'};const action=map[e.key];if(action){e.preventDefault();if(!e.repeat||(state.kind==='blocks'&&['left','right','down'].includes(action)))act(action);}
});
document.addEventListener('visibilitychange',()=>{if(document.hidden)setPaused(true);});window.addEventListener('blur',()=>setPaused(true));window.addEventListener('pagehide',()=>{if(mode==='play'){setPaused(true);persist();}});
function frame(now){advanceTo(now);if(mode==='play'&&!paused){audio.tick(state);draw();if(now-savedAt>1000)persist();if(reactionUntil&&now>reactionUntil){reactionUntil=0;decorate();app.querySelector('.signature-toast').hidden=true;}}requestAnimationFrame(frame);}
home();requestAnimationFrame(frame);loadCast().then(()=>{ready=true;home();}).catch(()=>{app.querySelector('.welcome').insertAdjacentHTML('beforeend','<p role="alert">캐릭터를 불러오지 못했어요. 페이지를 새로고침해 주세요.</p>');});
