/* global document, window, localStorage, requestAnimationFrame, performance */
import {createGame,stepGame,gameAction,readRecords,saveRecord,GAME_IDS} from './model.js';
import {GAMES,REACTIONS,extraValue,resultLine} from './catalog.js';
import {loadCast,paintDolls} from './cast.js';
import {drawGame,drawNext} from './render.js';
import {ArcadeAudio} from './audio.js';
const app=document.querySelector('#app'),audio=new ArcadeAudio();
let state,mode='loading',paused=false,last=0,storage,records=readRecords(),ready=false,held=null,reactions=0,offsetMs=0;
try{storage=localStorage;records=readRecords(storage);const n=Number(storage.getItem('rescene.rhythm.offset'));offsetMs=Number.isFinite(n)?Math.max(-200,Math.min(200,n)):0;}catch{/* Optional local storage. */}
function doll(id){return `<canvas class="doll" data-doll="${id}" role="img" aria-label="${Object.values(GAMES).find(g=>g.member===id).name} 캐릭터"></canvas>`;}
function header(play=false){return `<header class="topbar"><button class="brand" data-home aria-label="리센느 작은 오락실 홈"><span class="brand-mark">r.</span><span>리센느<small>작은 오락실</small></span></button>${play?'<button class="quiet" data-pause>잠깐 쉬기 Ⅱ</button>':'<span class="open-sign"><i></i> 다섯 친구가 기다려요</span>'}</header>`;}
function decorate(pose=0){if(ready)paintDolls(app,pose);}
function home(){
 audio.stop();held=null;mode='home';state=null;paused=false;records=readRecords(storage);app.dataset.state='home';delete app.dataset.game;
 app.innerHTML=`${header()}<section class="welcome"><div><p class="hello">바닷가 작은 오락실에 오신 걸 환영해요</p><h1>잠깐, 한 판 할래?</h1><p>좋아하는 멤버와 60초. 오늘의 작은 기록을 만들어 봐요.</p></div><span class="ticket">한 판의<br><b>작은 행복</b><span>✦ ✦ ✦</span></span></section><nav class="member-nav" aria-label="멤버 게임 바로가기">${Object.entries(GAMES).map(([id,g])=>`<a href="#machine-${id}">${g.name}</a>`).join('')}</nav><section class="machines" aria-label="다섯 멤버의 게임">${Object.entries(GAMES).map(([id,g])=>`<article id="machine-${id}" class="machine ${g.color}"><div class="marquee"><span>${g.name}의</span><h2>${g.title}</h2><span class="machine-badge">60초</span></div><div class="cabinet-screen"><div class="mini-scene ${id}"><canvas class="preview" data-preview="${id}" aria-hidden="true"></canvas></div><div class="host">${doll(g.member)}<span class="speech">${g.line}</span></div></div><div class="control-deck"><p>${g.hint}</p><button class="start" data-start="${id}" aria-label="${g.name}의 ${g.title} 시작" ${ready?'':'disabled'}>${ready?'바로 시작':'캐릭터 준비 중'} <span>▶</span></button><div class="cabinet-bottom"><span class="speaker-grill"></span><small>내 최고 기록 <b>${records[id].toLocaleString()}</b></small><span class="coin-slot"></span></div></div></article>`).join('')}</section><footer>비공식 팬 게임 · 멤버의 공개된 취향에서 출발한 창작 오락실<br>최고 기록은 이 브라우저에 저장돼요.</footer>`;
 decorate();app.querySelectorAll('[data-preview]').forEach(c=>{c.width=480;c.height=600;const s=createGame(c.dataset.preview);s.preview=true;if(s.kind==='drive'){s.elapsed=5;s.objects=[{lane:0,y:.23,kind:'star'},{lane:2,y:.45,kind:'cone'}];}if(s.kind==='blocks')s.board[11]=[1,1,0,0,2,2,3,3];if(s.kind==='rhythm')s.elapsed=3;if(s.kind==='catch')s.objects=[{lane:0,y:.25,blue:false},{lane:2,y:.4,blue:true}];drawGame(c.getContext('2d'),s);});
}
function controls(kind){
 if(kind==='photo')return '<button data-act="snap" class="shutter" aria-label="사진 찍기">◎ 찰칵!</button>';
 return `<button data-act="left" aria-label="${kind==='rhythm'?'왼쪽 박자':'왼쪽으로 이동'}">◀</button>${kind==='blocks'?'<button data-act="rotate" aria-label="조각 회전">↻<small>회전</small></button>':''}<button data-act="right" aria-label="${kind==='rhythm'?'오른쪽 박자':'오른쪽으로 이동'}">▶</button>${kind==='blocks'?'<button class="drop" data-act="drop">내려놓기 ↓</button>':''}`;
}
function start(kind){
 const g=GAMES[kind];if(!g||!ready)return;audio.stop();held=null;mode='play';paused=false;reactions=0;state=createGame(kind,{offsetMs});app.dataset.game=kind;app.dataset.state='playing';
 app.innerHTML=`${header(true)}<section class="play-layout ${g.color}"><aside class="companion"><button class="text-back" data-home>‹ 오락실</button><p class="host-name">${g.name}와 함께</p><h1>${g.title}</h1>${doll(g.member)}<p class="host-line" id="reaction">${g.line}</p><p class="key-guide">${g.keys}</p></aside><div class="game-cabinet"><div class="scoreboard"><div><small>남은 시간</small><strong id="time">60<em>초</em></strong></div><div><small>점수</small><strong id="score">0</strong></div><div><small>${g.extra}</small><strong id="extra">${extraValue(state)}</strong></div></div>${kind==='blocks'?'<div class="next-piece"><span>다음 조각</span><canvas id="next" width="160" height="80" role="img" aria-label="다음에 나올 조각"></canvas><small>점선은 놓일 자리</small></div>':''}<div class="playfield"><canvas id="game" width="480" height="600" tabindex="0" role="img" aria-label="${g.title} 게임 화면. ${g.hint}"></canvas><div id="overlay" hidden></div></div><div class="game-controls" aria-label="게임 조작">${controls(kind)}</div><p class="mobile-hint">${g.hint}</p></div><aside class="side-note"><p>내 최고 기록<strong id="best">${records[kind].toLocaleString()}</strong></p><div class="utility-buttons"><button class="quiet" data-help>하는 방법</button><button class="quiet" data-sound aria-pressed="${audio.enabled}">소리 ${audio.enabled?'끄기':'켜기'}</button></div><p class="short-guide">${g.guide}</p>${kind==='rhythm'?'<small>소리를 켜면 직접 만든 박자가 들려요.<br>판정 보정은 ‘하는 방법’에서 조절해요.</small>':''}</aside></section><p class="sr-only" id="announce" role="status"></p>`;
 decorate();draw();last=performance.now();app.querySelector('#game').focus({preventScroll:true});window.scrollTo(0,0);
}
function react(){
 if(!state.event)return;const event=state.event;state.event=null;const lines=REACTIONS[event];if(!lines)return;
 const line=lines[reactions++%lines.length];app.querySelector('#reaction').textContent=line;app.querySelector('#announce').textContent=line;const positive=!/miss|bump|early/.test(event);decorate(positive?1:2);if(positive&&event!=='place')audio.tone(state.kind==='rhythm'?880:720);
}
function advanceTo(now){
 if(mode==='play'&&!paused){let remaining=Math.max(0,(now-last)/1000);while(remaining>0&&!state.ended){const dt=Math.min(.05,remaining);stepGame(state,dt);remaining-=dt;react();if(held){held.wait-=dt;if(held.wait<=0){gameAction(state,held.action);held.wait+=.085;react();}}}if(state.ended)finish();}last=now;
}
function act(action){if(mode!=='play'||paused)return;advanceTo(performance.now());if(state.ended)return;gameAction(state,action);react();draw();if(state.ended)finish();}
function draw(){if(mode!=='play')return;drawGame(app.querySelector('#game').getContext('2d'),state);if(state.kind==='blocks')drawNext(app.querySelector('#next').getContext('2d'),state.next);app.querySelector('#score').textContent=state.score.toLocaleString();app.querySelector('#time').innerHTML=`${Math.ceil(state.remaining)}<em>초</em>`;app.querySelector('#extra').textContent=extraValue(state);}
function setPaused(value,help=false){
 if(mode!=='play'||state.ended)return;if(value){advanceTo(performance.now());if(state.ended)return;}paused=value;held=null;audio.stop();last=performance.now();app.dataset.state=value?'paused':'playing';const overlay=app.querySelector('#overlay');overlay.hidden=!value;
 if(value){const g=GAMES[state.kind];overlay.innerHTML=`<div class="pause-paper" role="dialog" aria-modal="true" aria-labelledby="pause-title"><h2 id="pause-title">${help?'이렇게 놀아요':'잠깐 쉬어가요'}</h2><p>${help?g.guide:'시간도 함께 멈췄어요.'}</p>${help?`<p class="dialog-keys">${g.keys}</p>`:''}${help&&state.kind==='rhythm'?`<label class="calibration">판정 보정 <output id="offset-value">${offsetMs}ms</output><input id="offset" type="range" min="-200" max="200" step="10" value="${offsetMs}"><small>소리보다 늦게 누르게 되면 + 쪽으로 조절해요.</small></label>`:''}<button class="start" data-resume>계속하기 ▶</button><button class="quiet" data-leave>이번 판을 끝내고 오락실로</button><small>완료하지 않은 점수는 저장되지 않아요.</small></div>`;overlay.querySelector('[data-resume]').focus();}else app.querySelector('#game').focus({preventScroll:true});
}
function finish(){
 if(mode!=='play')return;held=null;audio.stop();const previous=records[state.kind],saved=saveRecord(storage,state.kind,state.score);records=saved.records;draw();mode='result';paused=false;app.dataset.state='result';const next=GAME_IDS[(GAME_IDS.indexOf(state.kind)+1)%GAME_IDS.length],overlay=app.querySelector('#overlay');overlay.hidden=false;
 overlay.innerHTML=`<div class="result-paper" role="dialog" aria-modal="true" aria-labelledby="result-title"><span class="result-star">✦</span><p id="result-title">${state.score>previous?'새로운 최고 기록!':'오늘의 작은 기록'}</p><h2>${state.score.toLocaleString()}<small>점</small></h2><p>${resultLine(state)}</p><p class="result-message">${state.score>previous?'우리의 새 기록, 간직하자!':'같이 놀아서 즐거웠어!'}</p><button class="start" data-start="${state.kind}">한 판 더 ▶</button><button class="quiet" data-start="${next}">${GAMES[next].name}와도 놀기</button><button class="result-home" data-leave>오락실로</button><small>${saved.saved?'최고 기록은 이 기기에 저장했어요.':'기록을 저장할 수 없어요. 이번 점수는 화면에서 확인해 주세요.'}</small></div>`;
 app.querySelector('#best').textContent=records[state.kind].toLocaleString();app.querySelector('[data-pause]').hidden=true;app.querySelectorAll('[data-act]').forEach(b=>b.disabled=true);decorate(1);app.querySelector('#announce').textContent=`게임 완료. ${state.score}점.`;overlay.querySelector('[data-start]').focus();
}
app.addEventListener('click',async e=>{
 const b=e.target.closest('button');if(!b)return;if(b.dataset.start)start(b.dataset.start);else if(b.dataset.act&&e.detail===0)act(b.dataset.act);else if(b.hasAttribute('data-pause'))setPaused(!paused);else if(b.hasAttribute('data-help'))setPaused(true,true);else if(b.hasAttribute('data-resume'))setPaused(false);else if(b.hasAttribute('data-leave')){home();window.scrollTo(0,0);}else if(b.hasAttribute('data-home')){if(mode==='play')setPaused(true);else{home();window.scrollTo(0,0);}}else if(b.hasAttribute('data-sound')){const enabled=await audio.enable(!audio.enabled);if(b.isConnected){b.textContent=enabled?'소리 끄기':'소리 켜기';b.setAttribute('aria-pressed',String(enabled));}if(enabled)audio.tone();}
});
app.addEventListener('input',e=>{if(e.target.id==='offset'){offsetMs=Number(e.target.value);state.offset=offsetMs/1000;app.querySelector('#offset-value').textContent=`${offsetMs}ms`;try{storage?.setItem('rescene.rhythm.offset',String(offsetMs));}catch{/* Optional preference. */}}});
function pointLane(e){const rect=e.target.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*480;state.lane=Math.max(0,Math.min(2,Math.floor(state.kind==='drive'?(x-105)/90:(x-52.5)/125)));draw();}
app.addEventListener('pointerdown',e=>{if(mode!=='play'||paused||state.ended)return;const b=e.target.closest('[data-act]');if(b){e.preventDefault();b.setPointerCapture(e.pointerId);act(b.dataset.act);if(state.kind==='blocks'&&['left','right'].includes(b.dataset.act))held={action:b.dataset.act,wait:.28};}else if(e.target.id==='game'&&['drive','catch'].includes(state.kind)){e.preventDefault();e.target.setPointerCapture(e.pointerId);pointLane(e);}});
app.addEventListener('pointermove',e=>{if(e.target.id==='game'&&e.buttons&&mode==='play'&&!paused&&!state.ended&&['drive','catch'].includes(state.kind))pointLane(e);});
for(const type of ['pointerup','pointercancel','lostpointercapture'])app.addEventListener(type,()=>{held=null;});
window.addEventListener('keydown',e=>{
 if(mode==='home')return;const overlay=app.querySelector('#overlay');if(e.key==='Tab'&&overlay&&!overlay.hidden){const nodes=[...overlay.querySelectorAll('button,input')],first=nodes[0],end=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first.focus();}return;}
 if(mode!=='play')return;if(e.key==='Escape'){e.preventDefault();setPaused(!paused);return;}if(paused)return;if(['BUTTON','INPUT','A'].includes(e.target.tagName)&&(e.key===' '||e.key==='Enter'))return;
 const map=state.kind==='photo'?{' ':'snap',Enter:'snap'}:state.kind==='rhythm'?{ArrowLeft:'left',ArrowRight:'right',a:'left',A:'left',l:'right',L:'right'}:{ArrowLeft:'left',ArrowRight:'right',ArrowUp:'rotate',ArrowDown:'down',' ':'drop'};const action=map[e.key];if(action){e.preventDefault();if(!e.repeat||(state.kind==='blocks'&&['left','right','down'].includes(action)))act(action);}
});
document.addEventListener('visibilitychange',()=>{if(document.hidden)setPaused(true);});window.addEventListener('blur',()=>setPaused(true));
function frame(now){advanceTo(now);if(mode==='play'&&!paused){audio.tick(state);draw();}requestAnimationFrame(frame);}
home();requestAnimationFrame(frame);loadCast().then(()=>{ready=true;home();}).catch(()=>{app.querySelector('.welcome').insertAdjacentHTML('beforeend','<p role="alert">캐릭터를 불러오지 못했어요. 페이지를 새로고침해 주세요.</p>');});
