import {PUMP_SONGS} from './music.js';
/* global structuredClone */
import {GAME_IDS,INITIAL_LIVES,validStage,DURATION,createGame,stageTarget} from './model.js';
export const PROGRESS_KEY='rescene.arcade.journey.v1';
const integer=(n,min,max)=>Number.isInteger(n)&&n>=min&&n<=max;
const number=(n,min,max)=>Number.isFinite(n)&&n>=min&&n<=max;
const vector=(a,len,test)=>Array.isArray(a)&&a.length===len&&a.every(test);
const list=(a,max,test)=>Array.isArray(a)&&a.length<=max&&a.every(test);
export function stageGoal(kind,stage){return {target:stageTarget(kind,stage),unit:{drive:'파이리',blocks:'방울',photo:'빵',rhythm:'박자',catch:'격파'}[kind]};}
export function stageValue(s){return s.kind==='blocks'?s.popped:s.kind==='photo'?s.collected:s.kind==='catch'?s.defeated:s.hits;}
export function isStageClear(s){return !!s.stage&&stageValue(s)>=stageGoal(s.kind,s.stage).target&&s.hearts>0&&!s.endReason&&(s.kind!=='catch'||s.bossDefeated>0)&&(s.kind!=='rhythm'||s.remaining<=.001);}
export function emptyProgress(){return {version:2,games:Object.fromEntries(GAME_IDS.map(id=>[id,{stage:1,highest:1,hearts:INITIAL_LIVES,snapshot:null}]))};}
export function newRun(progress,kind){Object.assign(progress.games[kind],{stage:1,hearts:INITIAL_LIVES,snapshot:null});}
export function snapshotRound(s){if(!s||s.ended||!s.stage)return null;const copy=JSON.parse(JSON.stringify(s));delete copy.event;delete copy.breadFrames;delete copy.breadDrag;if(s.kind==='photo')copy.flash=0;return copy;}
export function saveRound(progress,s){if(s&&!s.ended){const e=progress.games[s.kind];e.stage=s.stage;e.highest=Math.max(e.highest,s.stage);e.hearts=s.hearts;e.snapshot=snapshotRound(s);}}
function validState(s){
 if(!number(s.elapsed,0,60)||Math.abs(s.elapsed+s.remaining-60)>.001||!integer(s.hearts,1,3))return false;
 for(const key of ['itemPickups','hits','combo','bestCombo','misses','popped','collected','defeated','nextEnemy'])if(key in s&&!integer(s[key],0,100000))return false;
 for(const key of ['damageCooldown','spawn','invincible','cooldown','flash','burst','burstCooldown','energyClock'])if(key in s&&!number(s[key],0,15))return false;
 if(s.kind==='drive')return s.chaseVersion===1&&integer(s.heat,0,4)&&number(s.fever,0,6)&&vector(s.holes,9,h=>h&&number(h.ttl,0,4.8)&&number(h.total,0,4.8)&&h.ttl<=h.total&&number(h.flash,0,.3)&&typeof h.gold==='boolean'&&(h.fake===undefined||typeof h.fake==='boolean')&&!(h.fake&&h.gold)&&(h.hitAt===undefined||number(h.hitAt,0,1))&&(h.reward===undefined||integer(h.reward,h.fake?-150:0,h.fake?0:600)));
 if(s.kind==='blocks'){const p=s.player;return s.mayVersion===2&&integer(s.mayLayout,1,2)&&number(s.speedBoost,0,10)&&number(s.sizeBoost,0,10)&&list(s.items,4,i=>i&&number(i.x,0,480)&&number(i.y,0,536)&&['speed','size'].includes(i.kind)&&number(i.ttl,0,12))&&p&&number(p.x,18,462)&&number(p.y,-50,536)&&number(p.vy,-550,1300)&&[-1,1].includes(p.facing)&&[-1,0,1].includes(p.dir)&&number(p.walk,0,.18)&&list(s.enemies,7,e=>e&&number(e.x,0,480)&&number(e.y,0,536)&&integer(e.home,0,3)&&[-1,1].includes(e.dir)&&number(e.trapped,0,5)&&number(e.vy??0,-550,1300)&&number(e.think??0,0,1.2)&&(e.angry===undefined||typeof e.angry==='boolean'))&&list(s.bubbles,8,b=>b&&number(b.x,-20,500)&&number(b.y,-100,600)&&[-260,260].includes(b.vx)&&number(b.ttl,0,1.8)&&(b.radius===undefined||[21,34].includes(b.radius)));}
 if(s.kind==='photo')return s.bakeryVersion===1&&integer(s.rollingPins,0,2)&&integer(s.breadCharge,0,3)&&typeof s.itemArmed==='boolean'&&(!s.itemArmed||s.rollingPins>0)&&vector(s.board,36,n=>integer(n,1,5)||integer(n,11,15))&&integer(s.selected,-1,35)&&integer(s.moves,0,18)&&integer(s.shuffles,0,2)&&list(s.clearedCells,432,n=>integer(n,0,35))&&list(s.hint,2,n=>integer(n,0,35));
 if(s.kind==='rhythm'){const notes=createGame('rhythm',{stage:s.stage,songId:s.songId}).notes;return Object.hasOwn(PUMP_SONGS,s.songId)&&number(s.offset,-.2,.2)&&vector(s.lastTaps,5,n=>number(n,-1,60))&&vector(s.feedback,5,n=>['','WAIT','MISS','GOOD','PERFECT'].includes(n))&&vector(s.glows,5,n=>number(n,0,.25))&&vector(s.notes,notes.length,(n,i)=>n&&n.at===notes[i].at&&n.lane===notes[i].lane&&['waiting','hit','miss'].includes(n.status));}
 return s.upgradeVersion===1&&integer(s.fireLevel,0,5)&&integer(s.volley,1,5)&&typeof s.bossSpawned==='boolean'&&integer(s.bossDefeated,0,1)&&integer(s.itemCount,0,100000)&&['','wand','fairy','meteor','wings'].includes(s.item)&&number(s.itemTime,0,10)&&number(s.itemClock,0,1)&&list(s.pickups,3,i=>i&&integer(i.lane,0,2)&&number(i.y,0,540)&&['wand','fairy','meteor','wings'].includes(i.kind))&&s.runnerVersion===1&&integer(s.lane,0,2)&&number(s.x,95,385)&&integer(s.squad,1,60)&&integer(s.gatesTaken,0,1000)&&number(s.gateSpawn,0,6)&&number(s.shotClock,0,.28)&&integer(s.charge,0,5)&&number(s.gateFlash,0,.8)&&typeof s.lastGate==='string'&&s.lastGate.length<=8&&list(s.gates,3,g=>g&&number(g.y,0,480)&&vector(g.options,3,o=>o&&(o.op==='add'&&integer(o.value,-6,6)||o.op==='multiply'&&o.value===2)))&&list(s.enemies,9,e=>e&&integer(e.id,0,100000)&&integer(e.lane,0,2)&&number(e.y,0,480)&&integer(e.hp,-100,1000)&&integer(e.maxHp,1,1000)&&typeof e.boss==='boolean')&&list(s.shots,80,b=>b&&number(b.x,71,409)&&number(b.y,40,455)&&integer(b.power,1,17));
}
export function restoreRound(data){try{
 if(!data||data.schema!==3||!GAME_IDS.includes(data.kind)||!validStage(data.stage)||data.ended!==false||!number(data.remaining,.000001,DURATION)||!integer(data.score,0,10000000)||!integer(data.rngState,0,4294967295))return null;
 const s=createGame(data.kind,{stage:data.stage,seed:data.rngState,hearts:data.hearts,offsetMs:(data.offset||0)*1000,songId:data.songId});
 for(const key of Object.keys(s)){if(key==='random'||key==='event')continue;if(!(key in data)){if(s.kind==='blocks'&&key==='mayLayout'&&(data.mayVersion===undefined||data.mayVersion===1))continue;if(s.kind==='rhythm'&&key==='songId'&&data.songId===undefined)continue;if(['damageCooldown','itemPickups'].includes(key)||s.kind==='blocks'&&data.mayVersion===undefined&&['mayVersion','items','speedBoost','sizeBoost'].includes(key)||s.kind==='photo'&&data.bakeryVersion===undefined&&['bakeryVersion','rollingPins','breadCharge','itemArmed'].includes(key)||s.kind==='catch'&&data.upgradeVersion===undefined&&['upgradeVersion','fireLevel','volley','bossSpawned','bossDefeated','pickups','item','itemTime','itemClock','itemCount'].includes(key))continue;if(s.kind==='drive'&&data.chaseVersion===undefined&&['chaseVersion','heat','fever'].includes(key))continue;return null;}s[key]=structuredClone(data[key]);}
 if(s.kind==='blocks'&&(data.mayVersion===undefined||data.mayVersion===1)){s.mayVersion=2;s.mayLayout=1;for(const e of s.enemies){e.vy??=0;e.think??=.8;e.angry??=false;}}
 if(s.kind==='catch'&&data.upgradeVersion===undefined)s.bossSpawned=s.enemies.some(e=>e.boss);
 if(!validState(s))return null;
 if(s.kind==='drive'&&data.chaseVersion===undefined){
  const active=s.holes.map((h,i)=>h.ttl>0?i:-1).filter(i=>i>=0),lanes=new Set();if(active.length>3)return null;
  for(const i of active){let lane=Math.floor(i/3);if(lanes.has(lane)){lane=[0,1,2].find(n=>!lanes.has(n)&&!s.holes.slice(n*3,n*3+3).some(h=>h.ttl>0));if(lane===undefined)return null;[s.holes[i],s.holes[lane*3]]=[s.holes[lane*3],s.holes[i]];}lanes.add(lane);}
 }
 s.event=null;return s;
 }catch{return null;}}
export function readProgress(storage){const progress=emptyProgress();let data;try{const raw=storage?.getItem(PROGRESS_KEY);if(raw?.length>200000)return progress;data=JSON.parse(raw);}catch{return progress;}if(![1,2].includes(data?.version))return progress;
 for(const id of GAME_IDS){const source=data.games?.[id],entry=progress.games[id];if(!source)continue;if(data.version===1){let cleared=0;while(cleared<5&&Array.isArray(source.cleared)&&source.cleared.includes(cleared+1))cleared++;entry.stage=entry.highest=cleared+1;const old=source.snapshot;if(old?.kind===id&&validStage(old.stage)&&old.stage<=entry.highest){entry.stage=old.stage;if(integer(old.hearts,1,3))entry.hearts=old.hearts;}}else{if(!validStage(source.highest)||!validStage(source.stage)||source.stage>source.highest||!integer(source.hearts,0,3))continue;entry.stage=source.stage;entry.highest=source.highest;entry.hearts=source.hearts;}const restored=restoreRound(source.snapshot);if(restored?.kind===id&&restored.stage===entry.stage&&restored.hearts===entry.hearts)entry.snapshot=snapshotRound(restored);}return progress;}
export function saveProgress(storage,progress){try{storage.setItem(PROGRESS_KEY,JSON.stringify(progress));return true;}catch{return false;}}
export function finishStage(progress,s){if(s.settled)return s.cleared;if(!s.ended&&!isStageClear(s))return false;const entry=progress.games[s.kind];if(s.stage!==entry.stage)return false;const cleared=isStageClear(s);s.settled=true;s.cleared=cleared;entry.snapshot=null;entry.hearts=s.hearts;if(cleared){entry.stage=Math.min(Number.MAX_SAFE_INTEGER,s.stage+1);entry.highest=Math.max(entry.highest,entry.stage);}return cleared;}
