/* global process, document, innerWidth, console */
import { createRequire } from 'node:module';
import { resolve, join } from 'node:path';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { once } from 'node:events';
import assert from 'node:assert/strict';
import { startServer } from '../../server/survival/server.mjs';
import { defaultPlan } from '../../server/survival/catalog.mjs';
// This check is explicitly a browser integration fixture. Live-model evidence is separate.
const require = createRequire(resolve(process.env.SURVIVAL_DEPENDENCIES || '.', 'package.json'));
const { chromium } = require('@playwright/test');
const dir = mkdtempSync(join(tmpdir(), 'rescene-browser-'));
const requests = [];
const runtime = { async run(req) {
  requests.push(req);
  const p = JSON.parse(req.prompt), agentId = req.agentId; let data = { agentId, text: '브라우저 시험용 응답: 호흡을 지킬 수 있는 무대를 함께 만들자.' };
  if (['proposal', 'discussion'].includes(p.task)) data = { ...data, plan: defaultPlan(), sourceRefs: [], memoryRefs: [] };
  if (p.task === 'vote') data = { ...data, approve: true, planHash: p.planHash };
  if (p.task === 'performance') data = { ...data, focus: 'breath', intensity: 1 };
  if (p.task === 'reflection') data = { ...data, eventRef: p.event.eventId, condition: '호흡', action: '호흡 연습', structuredAction: { focus: 'breath' }, expectedEffect: { metric: 'breath', direction: 'down' } };
  if (p.task === 'judge') data = { ...data, scores: p.evidence.map(e => ({ teamId: e.teamId, evidenceHash: e.evidenceHash, criteria: Array(5).fill(e.teamId === 'team-0' ? 19 : 10), reason: '브라우저 시험용 평가' })) };
  return { data, sessionId: `${agentId}-browser-fixture`, provider: 'fixture', usage: { input_tokens: 100 }, durationMs: 1 };
} };
const { server, game } = startServer({ port: 0, dataDir: dir, runtime }); await once(server, 'listening');
const browser = await chromium.launch({ headless: true }); const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
try {
  await page.goto(`http://127.0.0.1:${server.address().port}/survival.html`);
  await page.getByRole('button', { name: '팀 회의실 들어가기' }).click();
  await page.locator('#opponent-card').waitFor();
  await page.locator('#concept-hint').waitFor();
  await page.getByText('멤버 자료 관리', { exact: true }).click();
  await page.getByLabel('자료 제목', { exact: true }).fill('브라우저 등록 시험');
  await page.getByLabel('원문 HTTPS 링크').fill('https://example.com/interview');
  await page.getByLabel('발행일', { exact: true }).fill('2025-01-01');
  await page.getByLabel('발언 위치').fill('첫 번째 질문');
  await page.getByLabel('이용 근거').fill('브라우저 시험용 직접 작성 요약');
  await page.getByLabel('본인 발언의 짧은 요약').fill('등록 검증용 자료이며 실제 인물 발언으로 배포하지 않는다.');
  await page.getByRole('button', { name: '미검수 자료로 등록' }).click();
  const sourceRow = page.locator('[data-source-row]').filter({ hasText: '브라우저 등록 시험' });
  await sourceRow.getByText('미나미 · 미검수 · 미사용', { exact: true }).waitFor();
  await sourceRow.getByRole('checkbox').check();
  await sourceRow.getByRole('button', { name: '검수 완료 · 참고 허용' }).click();
  await sourceRow.getByText('미나미 · 사용자 검수', { exact: true }).waitFor();
  const sourceId = await sourceRow.getAttribute('data-source-row');
  await page.getByText('멤버 자료 관리', { exact: true }).click();
  await page.getByRole('button', { name: '다섯 멤버의 첫 제안 듣기' }).click();
  await page.getByRole('button', { name: '이 계획으로 의견 나누기' }).waitFor();
  assert.ok(JSON.parse(requests.find(r => r.agentId === 'minami').prompt).source.some(s => s.sourceId === sourceId));
  await page.getByLabel('팀원들에게 하고 싶은 말').fill('브라우저 시험: 후렴에서 호흡을 지키자.');
  await page.getByRole('button', { name: '이 계획으로 의견 나누기' }).click();
  await page.getByRole('button', { name: '나는 찬성 · 투표 시작' }).click();
  await page.getByRole('button', { name: '합의한 무대 시작' }).click();
  await page.getByRole('button', { name: '함께 돌아보고 경험 저장' }).click();
  await page.getByRole('button', { name: '다음 라운드로' }).waitFor();
  await page.locator('#growth-minami summary').click();
  await page.locator('#growth-minami').getByText('숙련 60.00 → 60.75 · 연습 3점', { exact: true }).waitFor();
  await page.getByText('멤버 자료 관리', { exact: true }).click();
  await sourceRow.getByLabel('철회 사유').fill('브라우저 철회 시험');
  await sourceRow.getByRole('button', { name: '자료 철회', exact: true }).click();
  await sourceRow.getByText('미나미 · 철회 · 미사용', { exact: true }).waitFor();
  await sourceRow.getByRole('checkbox').check();
  await sourceRow.getByRole('button', { name: '재검수 완료 · 다시 참고' }).click();
  await sourceRow.getByText('미나미 · 사용자 검수', { exact: true }).waitFor();
  await sourceRow.getByLabel('철회 사유').fill('최종 철회 상태 복원 시험');
  await sourceRow.getByRole('button', { name: '자료 철회', exact: true }).click();
  await sourceRow.getByText('미나미 · 철회 · 미사용', { exact: true }).waitFor();
  await page.getByText('멤버 자료 관리', { exact: true }).click();
  await page.getByRole('button', { name: '무대 리플레이' }).click();
  await page.screenshot({ path: join(dir, 'desktop.png'), fullPage: true });
  await page.reload(); await page.getByRole('button', { name: '다음 라운드로' }).click();
  await page.getByText('Round 2 / 10', { exact: true }).waitFor();
  await page.getByRole('button', { name: '다섯 멤버의 첫 제안 듣기' }).click();
  await page.getByRole('button', { name: '이 계획으로 의견 나누기' }).waitFor();
  for (const req of requests.slice(-5)) { assert.equal(req.sessionId, null); assert.deepEqual(JSON.parse(req.prompt).memory, []); assert.ok(!JSON.parse(req.prompt).source.some(s => s.sourceId === sourceId)); }
  await page.getByLabel('미나미 회복 PP', { exact: true }).fill('1');
  await page.getByLabel('팀원들에게 하고 싶은 말').fill('회복에 1PP를 쓰고 남은 포인트로 연습하자.');
  await page.getByRole('button', { name: '이 계획으로 의견 나누기' }).click();
  await page.getByRole('button', { name: '나는 찬성 · 투표 시작' }).click();
  await page.getByRole('button', { name: '합의한 무대 시작' }).click();
  await page.getByRole('button', { name: '함께 돌아보고 경험 저장' }).click();
  await page.getByRole('button', { name: '다음 라운드로' }).waitFor();
  assert.equal(game.state.rounds[2].plan.recovery[0], 1);
  assert.equal(game.state.rounds[2].growth.minami.recovery, 1);
  assert.equal(game.state.members.minami.hypotheses[0].observations[0].round, 2);
  await page.locator('#growth-minami summary').click();
  await page.locator('#growth-minami').getByText(/R2 시험됨/).waitFor();
  const archivedId = game.state.id;
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '새 시즌 준비' }).click();
  await page.getByText('Round 1 / 10', { exact: true }).waitFor();
  const currentId = game.state.id, beforeHistoryCalls = requests.length;
  assert.notEqual(currentId, archivedId);
  await page.getByRole('button', { name: '시즌 이력 불러오기' }).click();
  await page.locator(`[data-history="${archivedId}"]`).click();
  await page.locator('#history-view').getByText(/R2 · .*우리 팀 1위/).waitFor();
  assert.equal(game.state.id, currentId); assert.equal(requests.length, beforeHistoryCalls);
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: join(dir, 'mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ passed: true, mode: 'explicit-fixture', dir, flow: 'new → concept/opponent → sources → meeting/vote → performance/reflection → reload → round 2 recovery and hypothesis observation → archive read-only', consoleErrors: errors }));
} finally { await browser.close(); server.close(); await once(server, 'close'); }
